### ISSUE TITLE
Request: Support for charts with multiple series

### ISSUE THREAD

**Issue by yngndrw** [eez-open/studio#101]
Currently EEZ Studio does not support the creation of charts with multiple series. This forces scripts such as the oscilloscope waveform capture scripts to create a separate chart for each channel and does not allow for easy comparisons across channels.

Related issue: https://github.com/eez-open/studio/issues/69 (That issue covers the merging of existing charts within the terminal, this issue covers the programmatic creation of charts with multiple series.)

**Comment by mvladic** [comment]
Done.
