### ISSUE TITLE
EEZ Flow Milestone 2 - Interpreter for PC

### ISSUE THREAD

**Issue by prasimix** [eez-open/studio#103]
* Make “interpreter” that will support all the [above](https://github.com/eez-open/studio/issues/102) mentioned nodes and support all of existing page widgets (Text, Button, Container, List, Grid, …)
* Add support for "Text input" widget
---
Deliverables: New EEZ studio version published on GitHub and tagged as new prerelease

**Comment by prasimix** [comment]
Fixed

**Comment by glt248** [comment]
Hello, 
I'm exploring your amazing project, thank you ! I'm playing with dashboard projects and with this Milestone 2, I can understand you have developed an interpreter for PC. Can you give me a link on documentation on this part ? That will be perfect for my usecases to export a dashboard project and use it as standalone or with an interpreter. 

Thank you,

**Comment by mvladic** [comment]
You can run Dashboard projects within Studio, this is easy and preferred way. Here is [Studio Documentation](https://www.envox.eu/eez-studio-docs/) site.

You can also run Dashboard's standalone. Here is a repository that you can clone to start: https://github.com/eez-open/dashboard-standalone-app. Except README, there is no other documentation for this use case.

**Comment by glt248** [comment]
Thank you for your feedback!

I will look on it!

Le 24 avril 2024 17:15:08 GMT+02:00, "Martin Vladić" ***@***.***> a écrit :
