### ISSUE TITLE
Default script type is not accepted

### ISSUE THREAD

**Issue by prasimix** [eez-open/studio#106]
When a new script is created, default type (SCPI) is not accepted, and one has to change type and move back to SCPI if want to proceed. Tested with pre-release 0.9.8.1

![Screenshot at 2021-04-06 08-50-06](https://user-images.githubusercontent.com/15106476/113670395-5b4dbb80-96b5-11eb-993e-7644971a9434.png)

**Comment by mvladic** [comment]
Fixed.
