### ISSUE TITLE
Add Dark theme

### ISSUE THREAD

**Issue by prasimix** [eez-open/studio#114]
Add an option to easily switch between light and dark theme.

**Comment by mvladic** [comment]
You can switch theme by using Settings tab:

![image](https://user-images.githubusercontent.com/449788/134817777-b3fde7fc-caf6-488b-a4aa-33017d899260.png)

or through View - Swith to Dark Theme

![image](https://user-images.githubusercontent.com/449788/134817807-1d5d58d7-81e0-4b98-9aac-614419cfe200.png)

or with the Ctrl+Shift+T shortcut.

**Comment by prasimix** [comment]
Fixed
