### ISSUE TITLE
EEZ Flow Extension installation through Extension Manager

### ISSUE THREAD

**Issue by mvladic** [eez-open/studio#115]
Currently, eez-flow extensions are installed manually through `package.json` file which can be found here:

[Windows] `%APPDATA%\eezstudio\extensions`
[Linux] `~/.config/eezstudio/extensions`

Here is example of `eez-flow-ext-postgres` extension added to `dependencies` section inside package.json:

```
{
  "name": "extensions",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "eez-flow-ext-postgres": "latest"
  }
}
```

When `package.json` is modified, EEZ Studio should be restarted.

**Comment by prasimix** [comment]
Fixed
