### ISSUE TITLE
EEZ flow - SCPI action doesn't work with multiple inputs

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#120]
If I use multiple inputs in the SCPI action ({a}, {b}) this doesn't seem to work:

Using 1 parameter works:
![SCPIaction_channel_OK](https://user-images.githubusercontent.com/8796121/117566680-65017f00-b0b8-11eb-94a9-c4d35682b839.png)
![SCPIaction_dcvolt_OK](https://user-images.githubusercontent.com/8796121/117566681-6632ac00-b0b8-11eb-9486-c1742c316de5.png)

Using 2 parameters doesn't work:
![SCPIaction_not_working](https://user-images.githubusercontent.com/8796121/117566707-8d897900-b0b8-11eb-8cf8-07d68f6456a0.png)
![SCPIaction_log](https://user-images.githubusercontent.com/8796121/117566701-819db700-b0b8-11eb-8407-fe0851e2640e.png)

**Comment by mvladic** [comment]
Fixed!

**Comment by fietser28** [comment]
It is working, thanks!
