### ISSUE TITLE
EEZ Flow -  Unable to open flow if *.eez-project-ui-state file is empty

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#123]
If there is an *.eez-project-ui-state file next to the eez-project file and the ui-state file is empty I'm unable to open the project in studio.

Removing the empty file solves the problem manually. I think it is best if studio checks for the validity of the ui-state file.

This happened several times to me with a project, but I don't know under which condition the ui-state file becomes empty.

**Comment by mvladic** [comment]
Added validity check. It will silently continue if file is not valid.

**Comment by fietser28** [comment]
Works, thanks!
