### ISSUE TITLE
EEZ Flow Some SCPI commands causes studio to freeze

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#126]
The scpi command: 'source{channel}:volt:prog {setovp}' causes studio to freeze if it it triggered. The SCPI command is also not send to the BB3. Similar commands work fine.

![Screenshot 2021-05-16 at 14 22 55](https://user-images.githubusercontent.com/8796121/118396971-3c4a2e00-b652-11eb-8009-4c8f0f955d4e.png)

Other commands with multiple {} on one line seem to work fine. Similar but different from #120 

Example Flow (connect to BB3 before running the flow):
[ovpscpiTest.eez-project.zip](https://github.com/eez-open/studio/files/6489193/ovpscpiTest.eez-project.zip)

**Comment by mvladic** [comment]
Fixed.

**Comment by fietser28** [comment]
Working, thanks!
