### ISSUE TITLE
DCM220 update to 0.6 firmware fails in 1.7.1 MCU from EEZ-Studio-0.9.84.AppImage

### ISSUE THREAD

**Issue by johnsonm** [eez-open/studio#132]
I just successfully updated my initial crowdsupply campaign BB3 with two DCP405s and one DCM220 to 1.7.1 firmware. I used the AppImage of EEZ-Studio 0.9.84 to attempt to update the DCM220 from firmware 0.5 to firmware 0.6 (latest). I tried connecting at 19200, 115200, and 250000 bps and did not succeed with any connection speed.

Downloading gets to 100%, then it says that it is updating, then it fails. Sometimes it seems to just reboot, sometimes I see

> Preparing...

Then occasionally I see

> Failed to start update!
> Close

More often, the unit merely reboots without presenting that dialog.

I see log entries with `File download succeeded` immediately followed by `DCM220 R2B8 firmware update failed`

I have not attempted to update the firmware from microsd.

**Comment by mvladic** [comment]
Can't reproduce this problem with both Serial and Ethernet Connection.

I successfully downgraded DCM220 firmware to version 0.5 and again upgraded to version 0.6 multiple times.

I tested with the latest Studio (0,9.89) and BB3 firmware (1.8 alpha2).
