### ISSUE TITLE
Descriptions in flow component

### ISSUE THREAD

**Issue by prasimix** [eez-open/studio#141]
Add `Description` parameter in each flow component (except `Comment`) that will be displayed at the bottom of the component when `View description` option is enabled.

**Comment by fietser28** [comment]
![image](https://user-images.githubusercontent.com/8796121/150530607-b546d3c5-dd9c-402b-b22d-66fb7e289a6c.png)

Looks good to me. Close it?

**Comment by prasimix** [comment]
Fixed
