### ISSUE TITLE
Changes to variables in structs passed by reference are not updated in studio

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#154]
For Applet on FW 1.8-alpha2 and git version of studio.

If I create structs and pass the struct as an input to an action, then change one of the variables of the struct in the action this change is not shown in the debugger and screen in studio. It is shown correctly in BB3, so I assume the update is not propagating correctly from BB3 to studio. Don't know if the BB3 firmware or studio is missing this.

Applet:
![image](https://user-images.githubusercontent.com/8796121/139535683-d674d9d6-4d1e-4e53-82fc-1a071aa146a4.png)

BB3 output (correct):
![image](https://user-images.githubusercontent.com/8796121/139535866-d66c106f-36a8-42c7-9893-f511c681765d.png)

Screen in studio (incorrect):
![image](https://user-images.githubusercontent.com/8796121/139535941-19712e4f-e0a0-43c7-8ec6-9d263a85d2bb.png)

I don't mind the screen is not correctly, but the debug variables on the right are also incorrect.

**Comment by fietser28** [comment]
[structin2.eez-project.zip](https://github.com/eez-open/studio/files/7446726/structin2.eez-project.zip)
The used test flow.

**Comment by mvladic** [comment]
This should be fixed in the latest Studio & BB3 firmware. 

From this version of Studio it is required to set the type of value in action Input and Output.

![image](https://user-images.githubusercontent.com/449788/139542275-c8c11ce8-bc8f-4b67-ac41-441b66cbb7e6.png)
