### ISSUE TITLE
The bitmap preview remains after the bitmap is deleted

### ISSUE THREAD

**Issue by prasimix** [eez-open/studio#156]
Before delete:

![image](https://user-images.githubusercontent.com/15106476/140602255-eda46f4d-0481-4af5-b2d3-80fb8c1caee3.png)

... after deleting, preview is still visible:

![image](https://user-images.githubusercontent.com/15106476/140602274-77f2c39f-fdc9-4581-a24e-b34fa27b4c12.png)

**Comment by mvladic** [comment]
Fixed.
