### ISSUE TITLE
Math operations on imported data

### ISSUE THREAD

**Issue by prasimix** [eez-open/studio#16]
Various math operations should be possible on data once imported into ESW. That functionality can be organized in series of plug-ins that can be added over the time from various authors. This is a generic topic that can be break up in many new issues/tickets. Math operation can be performed on all data or selected data between cursors set by user. The following list are an example of possible operations:
 
**Basic operations Y-axis:**

* Max
* Min
* Peak-to-peak
* Average

**Advanced operations Y-axis:**

* [RMS](https://en.wikipedia.org/wiki/Root_mean_square) (root-mean-square)

**Basic operations X-axis:**

* [FFT](https://en.wikipedia.org/wiki/Fast_Fourier_transform)
* Period
* Frequency

**Advanced operations X-axis:**
Display as disabled all options that require two signals (A and B) on single signal graph/data. Create a new graph for displaying result of two signals operation.

* A + B
* A - B

**Comment by mvladic** [comment]
Math functions should be implemented as extensions.

**Comment by prasimix** [comment]
Partially completed (Max, Min, Peak-to-peak, Average and RMS) to be continued in M3.

**Comment by prasimix** [comment]
When ruler is activated, select e.g. 90% of current view. In that case drag operation is changed to graph part selection instead of zoom in.

**Comment by prasimix** [comment]
Fixed
