### ISSUE TITLE
Timeout (no response to IDN query)

### ISSUE THREAD

**Issue by endolith** [eez-open/studio#174]
I am getting this error even though it looks like it's responding to me:

![image](https://user-images.githubusercontent.com/58611/160014651-ebc5562e-3042-402b-8397-30dde697417f.png)

**Comment by prasimix** [comment]
If you're using USBTMC interface on Rigol then you can expect such error. Try Ethernet or VISA.

**Comment by prasimix** [comment]
See also: https://www.envox.eu/how-to/how-to-capture-a-screen-shot-from-an-rigol-dso-and-many-others/

**Comment by endolith** [comment]
> If you're using USBTMC interface on Rigol 

I'm not sure, I'm using this:

**Comment by prasimix** [comment]
That is VISA, it should work correctly with R&S VISA installed.

**Comment by endolith** [comment]
Can you give me any more hints?  

https://www.envox.eu/how-to/how-to-capture-a-screen-shot-from-an-rigol-dso-and-many-others/ says nothing about this except 

> EEZ Studio has been tested with R&S®VISA

After installing `RS_VISA_Setup_Win_5_12_3.exe` there is another option:

![2022-03-25 10_19_08-Rigol DS1102D - EEZ Studio](https://user-images.githubusercontent.com/58611/160145052-2befdf8d-ed5e-467a-a9a0-e3a7477bfb3e.png)

But both options produce the same "no response to IDN" error, despite obviously receiving a response to the IDN:

![image](https://user-images.githubusercontent.com/58611/160145244-a960c68b-fa5b-45fa-82a7-d54daa326418.png)

In the R&S Configure tool:

![image](https://user-images.githubusercontent.com/58611/160145344-35c9a993-e7e7-4701-80f7-455548bf6586.png)

I can create a new Resource, but it has the same string:

![image](https://user-images.githubusercontent.com/58611/160145490-061e90e9-839f-49f9-beaa-5b218f345fe9.png)

And still has the same confusing error

**Comment by prasimix** [comment]
If the R&S tool cannot establish a connection with the device, then EEZ Studio will not be able to do so via the VISA interface. The problem is possible on the Rigol side, or it can be up to the operating system, for example Linux has some problems with USBTMC with newer USB host controllers due to which it is not possible to establish a connection. If that model comes with Ethernet, you can try that interface.

**Comment by endolith** [comment]
It is establishing a connection, though?  It sends IDN and the scope responds, no?

**Comment by prasimix** [comment]
Yes, but if you're on Linux and using USBTMC then due to some buffer issue it cannot keep connection alive. Check this on the following [link](https://www.teuniz.net/DSRemote/):

![image](https://user-images.githubusercontent.com/15106476/160651338-1ffc33c4-48cc-4f36-9818-75bda26117f7.png)

**Comment by endolith** [comment]
I'm using Windows 10 Version	10.0.19044 Build 19044 and the USB VISA interface ![
](https://user-images.githubusercontent.com/58611/160043862-00e71685-44c8-4572-b4dd-aeeb40a08b62.png)

**Comment by prasimix** [comment]
Ok, I see. Don't know if that model has Ethernet interface to try it out, since that is all that I can suggest in this moment.

**Comment by prasimix** [comment]
In general, if you cannot establish connection with R&S tool you cannot expect that EEZ Studio via VISA interface works any better.
