### ISSUE TITLE
Nothing to build on IEXT project

### ISSUE THREAD

**Issue by BillyPocketNC** [eez-open/studio#175]
I am trying to create a fresh IEXT instrument definition, however, when I click build I get a "Nothing to build!" message.
Currently on Version 0.9.90 Build date 4/9/2022 3:47AM 
Running on Windows 11.

Also tried building the generic_scpi and got the same message.

Am I missing Something?

**Comment by mvladic** [comment]
To build extension(s), use `File - Build Extensions` from the menu:

![image](https://user-images.githubusercontent.com/449788/170238208-a18e3c1b-00f3-4291-8c31-c7db8b9ab93c.png)

**Comment by prasimix** [comment]
Closed, due to no response. Reopen if necessary.
