### ISSUE TITLE
EEZ flow：Use js expression in  Eval JS expresson Action

### ISSUE THREAD

**Issue by zddcool** [eez-open/studio#186]
+ We want to make a string input to convert an array output. 
+ We created a simple flow project as shown in the following image. We used a constant number as initial input, then we used js method 'toString' to covert number type to a string type. We called js 'split' method with seperator. 
![image-20220709111352887](https://user-images.githubusercontent.com/36909364/178090937-cbbe3935-d646-4858-aafa-efcce9e985d9.png)

+ In Node.js Env, the js expression as shown below returns an array, but in this flow project, the result is an empty object '{}'.
![image-20220709113035059](https://user-images.githubusercontent.com/36909364/178090954-98ed779b-0b18-47a0-9253-3d105c44fb64.png)
![image-20220709113058610](https://user-images.githubusercontent.com/36909364/178090956-4a3a46f0-4df5-47d0-9fc5-2f35745e60ff.png)

+ We also added an output port in Eval JS expresson Action Component, but the port returns nothing. In source code, you only add result as only output, and reslut port type is any, we may use certain type as output.
![image-20220709114040930](https://user-images.githubusercontent.com/36909364/178090962-7bd5d852-1c04-4025-887f-2f21f3baca1b.png)
![image-20220709114148722](https://user-images.githubusercontent.com/36909364/178090968-eb099113-de65-4b6b-94b2-dd99f28489b1.png)

**Comment by mvladic** [comment]
Fixed. You can now specify the type of the result:

![image](https://user-images.githubusercontent.com/449788/178100360-e5357edf-95e3-49bb-9eb2-8ae1b481e3ae.png)

![image](https://user-images.githubusercontent.com/449788/178100523-28fdf124-1d49-4936-bece-528e822c49c4.png)
