### ISSUE TITLE
Dashboards won't run/debug on OS X with 0.9.93

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#194]
If I create a new dashboard in 0.9.93 (hello world text) and run it or debug it (adding a start  and constant with a breakpoint), nothing happens at all in both cases.

The debug console of studio shows:

![image](https://user-images.githubusercontent.com/8796121/182228443-16779af8-d67c-49c0-abeb-fa3df7fae318.png)

Upon the start of studio the debug windows shows:

![image](https://user-images.githubusercontent.com/8796121/182228538-832a519c-0424-4ac3-a399-f7ca278ca602.png)
(the yellowish messages continue for a while)

The app.asar file is present:
![image](https://user-images.githubusercontent.com/8796121/182228683-013af8bd-f360-41a6-816a-a9907fe433c6.png)

Running OS X 12.15 (latest) on an M1 Pro CPU. Tested both the DMG and ZIP version, no difference. 
I think this also happened with 0.9.92 but didn't validate.

**Comment by fietser28** [comment]
If I press run the following exception appears (same as above but extended, giving more info):
![image](https://user-images.githubusercontent.com/8796121/182232347-c8ced9b8-ff97-406c-ab51-e4011caa2f48.png)

**Comment by mvladic** [comment]
Fixed in the latest 0.9.94 build.

**Comment by fietser28** [comment]
Works now. Thanks.
