### ISSUE TITLE
LVGL Font preview is scrambled (on OS X)

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#223]
Minor issue: On latest commit font preview in LVGL project looks scrambled:
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/8796121/206299550-8a522c0c-62f7-4738-b760-012787fd0c45.png">

The fonts are fine in editor, run, debug and on device itself. Only the preview is scrambled.

Of course it can also be just my build on OS X on M1.

**Comment by mvladic** [comment]
It works on Windows. Do you have an M1 or M2 Mac, i.e. did you build the ARM binary?

**Comment by mvladic** [comment]
BTW I tried but I can't build a functional ARM64 binary using github actions. I noticed that X86 binary is really slow.

**Comment by fietser28** [comment]
I have an M1 Pro, so ARM processor. I build native on arm. 

Latest commit of today ([lv_img_conv added](https://github.com/eez-open/studio/commit/19d7514b2ef571b693af10140b07e16dfcc59d79) )didn't result In a working studio so I reverted back to [improvements in animation timeline keyframe control points](https://github.com/eez-open/studio/commit/95da068dec5389635dc13d65643d6eef12ca0482) AND I had to revert back to node v16 (This is not unique to studio). That results in a working studio.

The latest images on GitHub don't work on my M1: Studio starts but page stays blank.

**Comment by mvladic** [comment]
The version was broken on Windows also. It is fixed now.

**Comment by fietser28** [comment]
Build is working now (tested not. Font previews are still scrambled, they are working in editor, run and on mcu.

**Comment by mvladic** [comment]
I can't reproduce this problem on M1 Pro. Can you share the details which font file (TTF) you are using?

**Comment by fietser28** [comment]
https://www.1001fonts.com/digital-7-font.html
Both the digital-7-regular and the digital-7-mono

**Comment by mvladic** [comment]
Still, can't reproduce. I tried both fonts files with x86 and arm64 version and with various font sizes.

**Comment by fietser28** [comment]
Probably something with my build. It's also not an important bug, just cosmetic.

**Comment by fietser28** [comment]
Narrowed it doen: If I change the bits per pixel (bpp) to 4 then the fonts are scrambled. The default bpp of value 8 works fine.

**Comment by mvladic** [comment]
Fixed

**Comment by fietser28** [comment]
Confirmed, thanks.
