### ISSUE TITLE
LVGL widget TextArea doesn't accept all forms of expressions

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#225]
When setting the Text of a TextArea widget to a variable it works.

When setting the Text of a TextArea to an expression (e.g.   my float + "U") both in studio (with error: "Failed to assign Text in Textarea widget: (null)") and on MCU (ui task freezes).

Not working:
![image](https://user-images.githubusercontent.com/8796121/206736537-1d6c0bea-5d44-4059-ab89-2f2694cee865.png)

Works:
![image](https://user-images.githubusercontent.com/8796121/206736693-80e8c167-fbd3-4b71-8df7-0ba4e6afa468.png)

Also working (this is a label not a texture):
![image](https://user-images.githubusercontent.com/8796121/206737643-5fe5c725-4532-4842-9341-316f21de1a89.png)

**Comment by mvladic** [comment]
Fixed.

**Comment by fietser28** [comment]
Working. Thank you.
