### ISSUE TITLE
Flow: comment/description box size is off for small components 

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#231]
just cosmetic:

<img width="821" alt="image" src="https://user-images.githubusercontent.com/8796121/209677408-9de576d0-1134-4a76-b54c-a191ccfcfc09.png">

The yellow description boxed appear to have a later large minimum width.

**Comment by mvladic** [comment]
It's intentional - the minimum size is 200px

**Comment by mvladic** [comment]
Minimum size exists so it doesn't wrap to much longer descriptions. Maybe it should be centered with the widget so it doesn't look off.

**Comment by mvladic** [comment]
For example, not centered:

![image](https://user-images.githubusercontent.com/449788/209678510-f6d5007b-dda4-4933-81da-1b6676e4c391.png)


Centered:

![image](https://user-images.githubusercontent.com/449788/209678490-cd14483a-73ae-40a0-be45-3b5a3f46cd09.png)

**Comment by fietser28** [comment]
Centered looks good for larger text.

For small texts (text width is a single line and less then width of component) I would make it the width of the widget.
In that way there is no 'empty box' sticking out.

**Comment by mvladic** [comment]
I don't how to do in CSS: remove min-width if smaller text. But, maybe I should remove `min-width: 200px`. In that case your example will look like this:

![image](https://user-images.githubusercontent.com/449788/209680297-095349d6-feff-437a-b9e4-59cbbb5aa50b.png)

**Comment by fietser28** [comment]
This looks better to me, but that is personal taste. You probably should keep a small minimum.

**Comment by mvladic** [comment]
This is already at minimum defined for the action component.

**Comment by mvladic** [comment]
I removed the "min-width" of 200px for comments. It will always be the same width as the component the comment refers to. "min-width" for the component is 87px (don't ask me how I got that number :) ).

**Comment by fietser28** [comment]
Looks good now to me. Thanks.
