### ISSUE TITLE
LVGL Flow: textarea expression is filtered by allowed characters

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#232]
In the textarea widget: If the text is set to be an expression the content of the expression is filtered by the accepted characters field. I suspect this should only be the case if the text is a text and not an expression.

Example:
<img width="855" alt="image" src="https://user-images.githubusercontent.com/8796121/209706509-2af4a814-89a6-4cdf-8428-9ea1964b5adf.png">

**Comment by mvladic** [comment]
Fixed

**Comment by fietser28** [comment]
Thanks.
