### ISSUE TITLE
Flow: change seqin handle of user actions

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#233]
Current sequin handling of user actions has an inconsistency:
![image](https://user-images.githubusercontent.com/8796121/209819449-afbcccf1-0c3e-4276-8be1-498a7851ca3c.png)
The action str2value is still executed if values are received on the action, despite the error message.

Discussed fix:
- always add a seqin handle to a user action. 
- If the user action has a start action the sequin handle will become mandatory (giving build error) .
- If the user action has NO start action, the seqin handle will be optional (nothing connected doesn't result in build error).

In both cases the condition to execute action is when some input receives data and all other inputs already received their data. Consequently, if the user action has a start action and there is no connection to seqin input (error will be reported) then this action will never execute. Once action is executed, its seqin input is cleared and data inputs are not cleared, i.e. they keep their last values. So we need to receive some data again on seqin input so it can execute again.

This behaviour is also consistent with other built-in components.

**Comment by mvladic** [comment]
Fixed.

Here is the project file used to test this ticket:

[test_user_action.zip](https://github.com/eez-open/studio/files/10320119/test_user_action.zip)

There is 4 cases tested:

- user action **with** start when there is a connection to start
- user action **with** start when there is **no connection** to start
- user action **without** start when there is a connection to start
- user action **without** start when there is **no connection** to start
