### ISSUE TITLE
Shortcuts and groups view enhancements

### ISSUE THREAD

**Issue by prasimix** [eez-open/studio#248]
* [x] In `Group` section (Shortcut tab) add shortcuts that come from IEXT
* [x] Add `Hide IEXT shortcuts` checkbox
 
![image](https://user-images.githubusercontent.com/15106476/225331827-defff93a-ca75-4078-b455-99d05851c118.png)

**Comment by mvladic** [comment]
Checkbox is `Show IEXT shortctus`. Default is enabled.

**Comment by prasimix** [comment]
Fixed
