### ISSUE TITLE
Make sample projects accessible on New project page

### ISSUE THREAD

**Issue by prasimix** [eez-open/studio#255]
We currently have several sample projects located in different repositories and folders, which makes it difficult to find them and use them as a template for creating a new project. All previous and future projects should be put in one place and they must be accessible through the New project page.

For each shown project example, we can display the following information:

* Example name
* Short description
* Target platform
* Link to target platform info
* Type of project
* Screen resolution / page dimensions (for a dashboard project) / none (for a non-GUI project)

This is a list of existing example projects and resources:
* https://github.com/eez-open/stm32f469i-disco-lvgl-demo
* https://github.com/eez-open/bb3-dashboard-app
* https://github.com/eez-open/stm32h745i-disco-lvgl-demo
* https://github.com/eez-open/MStack-DMA-eez-flow-demo
* https://github.com/eez-open/Nscreen_32-esp32-eez-flow-demo
* https://github.com/eez-open/esp32-lvgl-eez-demo
* https://github.com/eez-open/lvgl-web-demo
* https://github.com/eez-open/stm32f469i-disco-eez-flow-demo
* https://github.com/eez-open/sdl-eez-flow-demo
* https://github.com/eez-open/lvgl-template-web
* https://github.com/eez-open/studio/tree/master/docs/tutorial
* https://github.com/eez-open/studio/tree/master/resources/project-templates

A new repository is opened for managing all project samples: https://github.com/eez-open/eez-project-examples

**Comment by goran-mahovlic** [comment]
Zephre is missing

RP2040 is also missing

https://github.com/eez-open/raspberrypi-pico-tft-eez

Raspberry PI bare metal is bit problematic - we could ask authors how to rework to make it as separate project and original repositories as submodules...

https://github.com/goran-mahovlic/circle-eez

https://github.com/goran-mahovlic/circle-stdlib-eez

**Comment by prasimix** [comment]
Fixed
