### ISSUE TITLE
EEZ Flow: Make style from current object style settings

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#258]
During the design of a UI, I often make a new object and tweak it until I like the style. At that moment I would like to have a simple way (button) to make the settings of this object into a new style. 

Currently I create the object and manually create the style afterwards by copying all the settings I changed.

**Comment by mvladic** [comment]
Done.

If there are some modification in widget styles them following menu will be available:

![image](https://github.com/eez-open/studio/assets/449788/3298639c-b9e7-4950-a91c-8f2ddfc8d9fa)

- Reset All Modification: this will reset (clear) all local modification for this widget
- Create New Style: this will create a new style from local modifications and also make this widget use newly created style.
- Update Style: if widget is using some style and have some local modification then it will update that style with those local modifications
