### ISSUE TITLE
SCPI terminal: add option to link the SCPI command input to the SCPI documentation search.

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#267]
When using the SCPI terminal in studio I frequently use the feature to lookup SCPI commands in the 'documentation browser'. I need to frequently switch between the SCPI input line and the documentation search field (using mouse).

I think it would be very nice to have a checkbox (above the search box of the documentation browser or a link icon in the search box?) to link the command input with the documentation browser: If this checkbox is on then the SCPI documentation search dynamically follows my command input:

![image](https://github.com/eez-open/studio/assets/8796121/158390f6-19b0-46bb-add7-c499cf202205)

**Comment by mvladic** [comment]
Done.

**Comment by fietser28** [comment]
Works. Thank you!
