### ISSUE TITLE
[LVGL] Color themes

### ISSUE THREAD

**Issue by prasimix** [eez-open/studio#271]
- [x] Themes panel:

![image](https://github.com/user-attachments/assets/663ef10c-135b-4a52-81ef-e0730d658621)

- [x] Drag & drop color from the Themes panel to the any color field:

![theme_set_color](https://github.com/user-attachments/assets/9de68172-8700-427c-9a18-da779ccc4f1d)

- [x] Use `SetColorTheme` action to select active theme. Theme is given by its name.
- [x] Use `Flow.themes()` function to get the string array containing the names of themes.

![image](https://github.com/user-attachments/assets/cf09fc97-85c9-4695-8f34-49e971de841b)
![image](https://github.com/user-attachments/assets/ff7a8a18-19e0-488f-a9b0-6f1008fcd033)

- [x] Generated code (declared in `screens.h`):

```
enum Themes {
    THEME_ID_LIGHT,
    THEME_ID_DARK,
};
enum Colors {
    COLOR_ID_COLOR,
    COLOR_ID_BACKGROUND_COLOR,
    COLOR_ID_MY_COLOR,
    COLOR_ID_MY_COLOR_1,
};
void change_color_theme(uint32_t themeIndex);
extern uint32_t theme_colors[2][4];
```

- [X] Change current theme from the C/C++ code:

```
change_color_theme(THEME_ID_LIGHT);
```

- [X] Get color value from the C/C++ code:

```
theme_colors[THEME_ID_LIGHT][COLOR_ID_MY_COLOR]
```

**Comment by tylercamp** [comment]
+1, was going to request a "color palette" feature, but this would work too

**Comment by herrfrei** [comment]
+1

**Comment by yaredna** [comment]
Looking forward to revision 0.19.0, as the lack of theme in EEZ Studio / LVGL is a show stopper for now. Putting migration project on hold.

**Comment by andrearizzello** [comment]
+1

**Comment by mvladic** [comment]
Implemented.

**Comment by yaredna** [comment]
Hello mvladic: 

Two questions:
. color themes: still on track for next month ? 
. in LVGL 8.4, we can't retrieve the needle indicator from a meter to set the value. Do you have a work around to expose the indicator as a global variable or something similar ? Best regards !

**Comment by mvladic** [comment]
> . color themes: still on track for next month ?

Yes, color themes are already implemented.

> in LVGL 8.4, we can't retrieve the needle indicator from a meter to set the value. Do you have a work around to expose the indicator as a global variable or something similar ? Best regards !

It doesn't make sense to discuss needle indicator in this issue. It is best to repeat this question on [Discord](https://discord.com/channels/511131497801973761/1207347896857530400).
