### ISSUE TITLE
no response to IDN query

### ISSUE THREAD

**Issue by EdizonTN** [eez-open/studio#272]
Hello,
I have a problem with create my own Instrument.

In YAT serial terminal I try to send IDN command to instrument - Result was OK:
![2023-06-26 13_36_21-YAT -  Terminal1 _  - COM4 - Closed](https://github.com/eez-open/studio/assets/48570749/2c74a1af-7473-4d7e-8cd2-21f482e77738)

In EEZ Studio into my created instrument I enter string **"SN:V1.80;"** into IDN field (also with quotation marks).
Instrumet was checked and installed as extension.

In new project I try to add this instrument and try to connect - without success, with message "no response to IDN query".
But in command history I see an answer (see screenshot)! 
Pls, Where is a problem?
EEZ Studio: Version 0.9.99, OS: Windows 10.
Connected instrument: Twintex TP-3303U - Multiple Output Programmable Linear DC Power Supply
Connected via USB cable (In Twintex is a FTDI USB/TTL Serial converter), in EEZ selected serial comm.

![2023-06-26 13_33_16-Home - EEZ Studio](https://github.com/eez-open/studio/assets/48570749/03645d1a-7a21-4ca1-a504-061472c5f882)

**Comment by mvladic** [comment]
If this instrument is using <CR> as line end indicator then that explains why the IDN detection does not work - Studio is expecting <LF> as line end indicator.

I built a version which should also work with <CR> as line end indicator, you can download it from here:

https://www.dropbox.com/s/x2d4c8by0hv3jgg/EEZ%20Studio%20Setup%200.10.1.exe?dl=0

**Comment by EdizonTN** [comment]
Perfect!
It's work now!
Thanks!

![2023-06-27 11_58_21-Settings](https://github.com/eez-open/studio/assets/48570749/9b64bb70-7082-44de-87e6-84ecf2fa1489)
