### ISSUE TITLE
Serial timeout delay and handling improvements

### ISSUE THREAD

**Issue by FractalEngineer** [eez-open/studio#280]
My 2007 Motech LPS-505N appears to have issues communicating with EEZ Studio that seem to be handled differently with the proprietary BK software

Here are the key takeaways from the debugging process we've followed on the discord (starting from https://discord.com/channels/511131497801973761/821772335865659522/1145288737589313607)

1.  When operated in EEZ Studio, the serial link is very likely to time out after a few queries/commands. It then take a long time for Studio to alert it, and when it does no command/query can be sent to the unit anymore. (Sending an unknown/unimplemented command/query causes it too) >> The only way to unfreeze the situation is to dis/reconnect the instrument

2. Increasing loop delay or separating queries by even up to 1s does not resolve the issue, showing it not to be a matter of overwhelming the unit with data

3.  When operated in the Proprietary BK software, like in this instance with an automated voltage sweep program, we can notice that the timeouts remain present, but the timeout delay appears much faster, in the order of ~5ms

![image](https://github.com/eez-open/studio/assets/40505552/dd331839-f261-410f-8440-ae796e36f8cd)

4.  Furthermore, in this instance the instrument seems to simply skip the response and carry on to the next command

5. When manually operated in Keysight Connection Expert serial monitor, we are able to adjust the timeout delay. If I try lowering it to 5ms I actually get a decently smooth operation

Considering all those factors, I reckon these 2 improvements may bring a lot more flexibility to how some instruments manage timeouts:

1. Revising the timeout behavior to allow the communications to carry on without needing to break the connection with the instrument to reset the fault 

3. Adding the option to set the timeout delay for each instrument; in the instrument connection settings panel perhaps?

Hoping that's all clear enough :)

Cheers!

__Yves

**Comment by mvladic** [comment]
Timeout and Delay added to the Instrument Connect dialog:

![image](https://github.com/eez-open/studio/assets/449788/785348d6-0b02-4c6c-a12f-45fbad3031d2)

Also, Timeout and Delay added to the SCPI action component:

![image](https://github.com/eez-open/studio/assets/449788/787ec9c5-d0de-40f0-8696-0e32d5a4b667)

If specified this will override Timeout and Delay from the Instrument Connection dialog. Set to `null` value if you don't want to override it.

To catch Timeout exception in SCPI action component, enable "Catch error" as usual:

![image](https://github.com/eez-open/studio/assets/449788/47d555dd-6b4c-4c32-bd7f-455ea888e4e2)

![image](https://github.com/eez-open/studio/assets/449788/27237b03-4e4c-434a-a126-9026fd1d43be)
