### ISSUE TITLE
A few bugs/typos found in flow

### ISSUE THREAD

**Issue by FractalEngineer** [eez-open/studio#281]
I've been keeping track of possible bugs/enhancements while going through the process of making my own test procedures;

In this thread, I'd like to leave a continued list of bugs(?) and typos issues :)

* [ ] 1. Dropdown widget doesn't seem to work with 2 items; need 3 minimum?
![image](https://github.com/eez-open/studio/assets/40505552/09283aba-114c-423c-a8cd-c7fecd349ad1)

* [x] 2. Slider indicator in the flow GUI demo seems broken -- Also is nothing supposed to happen when clicking the input boxes?
![image](https://github.com/eez-open/studio/assets/40505552/8de1157f-72dd-44aa-935b-8f2d28e74e87)

* [x] 3. Default button widget has one extra "t"
![image](https://github.com/eez-open/studio/assets/40505552/b12deb17-2c3c-4d24-9bdc-9f7447dc5d37)

**Comment by mvladic** [comment]
1. Can't reproduce this problem. What type of project is this?
2. Fixed.
3. Fixed.
