### ISSUE TITLE
SCPI action widget doesn't accept spaces in the command

### ISSUE THREAD

**Issue by FractalEngineer** [eez-open/studio#285]
The SCPI action widget seems to refuse to build my scpi command even though it works fine in the monitor

The error seems attributed to the spaces, which appear required in my instrument datasheet

Fortunately, it seems to work without space, but perhaps something to look into

![image](https://github.com/eez-open/studio/assets/40505552/d91ea7a9-23bf-48f2-9baa-9d5612bb1112)
![image](https://github.com/eez-open/studio/assets/40505552/6cdcb050-60c7-4342-a688-63a1ef182c3b)
![image](https://github.com/eez-open/studio/assets/40505552/2538fa8b-2401-41c4-976c-78163bdea484)

**Comment by mvladic** [comment]
It seems that the SCPI specification does not allow spaces between `:` and mnemonics. Since in the case of your instrument it also works without spaces, I suggest that we close this ticket.
