### ISSUE TITLE
IEXT builder honours .gitignore definition or ignore . files

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#288]
If LibreOffice still has one or more of the .odt files open while generating the IEXT .zip, the lock files also get into the zip file.
Same goes for apple's .DS_Store files.

I'm using the doc/src folder convention. 

I see 2 solutions for generating cleaner zip files:
- studio honours what is specified in the .gitignore file. Maybe this has complications/side effects
- the inclusion of the doc directory shouldn't include filenames starting with a .

**Comment by mvladic** [comment]
This is done:

- the inclusion of the doc directory shouldn't include filenames starting with a .

**Comment by fietser28** [comment]
Works fine!
