### ISSUE TITLE
IEXT builder: numbers are ignored in import of discrete range type

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#289]
In the IEXT builder: If I define a discrete range for a SCPI parameter and the range has numbers in them, these are ignored during import.

E.g.
If I have '6|60|600|MIN|MAX|AUTO' in the ODT file. I get 'MIN|MAX|AUTO'.

Workaround is to manually correct this in studio afterwards.

**Comment by mvladic** [comment]
Fixed.
