### ISSUE TITLE
EEZ Flow: Can't use queries without ? in SCPI component

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#292]
Siglent has SCPI queries (e.g. SCDP) not ending with a question mark (?)...
The SCPI component doesn't accept this. It thinks this is an error:

![image](https://github.com/eez-open/studio/assets/8796121/429fcb65-0720-4209-87b1-beea54d7a5ca)

(the SCDP command is defined as a data block response in the IEXT and it is working fine in the SCPI terminal)

Am I missing something or do we need a feature like:

```
blowout =? SCDP
``` 
to explicitly tell the SCPI component the command is actually a query?

**Comment by mvladic** [comment]
As you suggested, I added the "=?" operator for this case.

**Comment by fietser28** [comment]
Works!
