### ISSUE TITLE
A JavaScript error occured in the main process

### ISSUE THREAD

**Issue by demondev** [eez-open/studio#298]
Hi,

I have just downloaded and installed this https://github.com/eez-open/studio/releases/download/v0.10.4/EEZ.Studio.Setup.0.10.4.exe and followed the Windows install instructions here https://github.com/eez-open/studio#windows

When lauching I am confronted with the following error.

![image](https://github.com/eez-open/studio/assets/4218606/2e96bece-ad5e-4448-ae43-c0f04f2e743c)

Any ideas ?

**Comment by demondev** [comment]
Removing 0.10.4 then installing 0.10.3 and the application loads fine.

**Comment by mvladic** [comment]
0.10.4, while still in development, was accidentally released. Unfortunately, it was also broken build. Until next official build, we recommend to use 0.10.3.

**Comment by demondev** [comment]
Understood, thanks for the response.
