### ISSUE TITLE
BB3-Dashboard Slot2 (3rd slot) fails to set U or I. Numberinput doesn't disappear. Channel 1 and 2 work fine 

### ISSUE THREAD

**Issue by ronnyvs1** [eez-open/studio#299]
Hi all,
Already thanks for helping... and an amazing tool!!!!
I did make a change from the BB3-dashboard, to make it work with Rigol power supply's.
actually everything seems to work fine...
Channel 1 en 2 are working great... ,

Channel 3 output enable also works,  meters showing right values etc.. but....
When i want to set channel 3 it has the problem that it won't set the voltage or current.
when i hit the "Ok"-button, the settings are not being managed by EEZ-studio. The numberinput should disappear but stays visible.
also the number input "is_open" stays "true"
It also gives the next error message:

**Error: Failed to evaluate variable no. 1 in SetVariable: Array value expected**

 (see image)

in the background everything else stil works, but i can't control it , because the numberinput stays visible...

Hope someone can help me..
friendly regards,
Ronny
![BB3_Dashboard_failure](https://github.com/eez-open/studio/assets/122125131/4cc342bb-d6a3-45fd-a876-acc5ef394533)

**Comment by mvladic** [comment]
Congratulations, you found a bug! 

In `NumberInput` user widget, `SetVariable` should be corrected (add `- 1` in two places):

![image](https://github.com/eez-open/studio/assets/449788/ce3126fd-09c2-45b2-9709-9bd268d2b529)

I will fix it (officially) next week when I'm back from vacation.

**Comment by ronnyvs1** [comment]
Thank you for your help!
Now it works very well...
i made it , to post it, so that other people can remote control the latest Rigol power supply's.
I only want to do the basics, so that other people can modify it with more options etc.

maybe a last question,
How can i convert this from a project to an instrument and i want to add the Connect-Disconnect button...?

but for now, enjoy your vacation!!!

Friendly regards and thanks for your help!!
Ronny

**Comment by mvladic** [comment]
> How can i convert this from a project to an instrument and i want to add the Connect-Disconnect button...?

There is an option for the instrument project (IEXT) to include one or more dashboard projects. For example, here is how BB3 dashboard is added to the BB3 IEXT:

![image](https://github.com/eez-open/studio/assets/449788/d8995d45-bf21-4037-bd26-00e7d3434a30)

When dashboard is added to the instrument there is no need to add separate Connect/Disconnect buttons as regular instrument Connect/Disconnect buttons will be used:

![image](https://github.com/eez-open/studio/assets/449788/4a7cc3b5-f4f4-4102-9f67-0d54795af016)

**Comment by mvladic** [comment]
Fixed.
