### ISSUE TITLE
[LVGL] Add lv_tabview

### ISSUE THREAD

**Issue by dolence** [eez-open/studio#301]
The object `lv_tabview` used to organize the content using tabs is missing.

Example: [lv_tabview](https://docs.lvgl.io/master/widgets/tabview.html)

**Comment by Jvsjvs** [comment]
Please also add the: "Container" object. This is used frequently to create an hierarchy in the UI layout structure (e.g. in the tabview).

Thanks

**Comment by mvladic** [comment]
> Please also add the: "Container" object. This is used frequently to create an hierarchy in the UI layout structure (e.g. in the tabview).

In the latest version I added Container widget exactly for the purpose you described. So you can add two container widgets to the TabView, one for the Bar and another for the Content. When you do this then you should put Tab widgets under the Content. This configuration is useful when you want to style Bar and Content part of the TabView. This is optional, if you don't need to style TabView then you can place Tab widgets immediately under TabView.

![image](https://github.com/eez-open/studio/assets/449788/872b2feb-e58f-4887-973d-8666df0c3aec)

**Comment by Jvsjvs** [comment]
Great, thanks!

**Comment by paolodecaro** [comment]
Buonasera sto cercando di fare il tuo esempio senza successo. Gentilmente potresti postarmi il codice del tuo esempio. Grazie

**Comment by Zmmfly** [comment]
Hi, i found cannot customize the border side of selected bar with Tabview in EEZ Studio 0.26.2 and LVGL 9.4.0, but work ok with LVGL 8.4.0

**Comment by MartinRasche** [comment]
Even with this separation in containers, i have not found a way to change the color of the active tab. 
Is that even possible in EEZ Stduio, changing the active tab color of a tabview in the editor, 
or do i have to implement a custom tabview with event handlers?
