### ISSUE TITLE
Flow: 'Find All references' displays actions not actually connected 

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#302]
Symptom: Searching for all references to a specific action in the project results in a lot of incorrect hits. It is an inconvenience in the UI, the flows seem to work fine.

Example with a single error (the search was for find all references to dummyAction):

<img width="1759" alt="image" src="https://github.com/eez-open/studio/assets/8796121/c1de19da-9272-43f2-bbf3-7bd754046eab">

Attached is the project. It was created as a new project with latest GitHub version. 
[referencesbug.eez-project.zip](https://github.com/eez-open/studio/files/14228785/referencesbug.eez-project.zip)

Looking in the eez-project file, it seems all evenHandlers of handlerType Flow also have a filled action field. This looks incorrect to me:
Event handler section of the 'Hello, world!' label:
```
"eventHandlers": [
            {
              "objID": "ad28c923-1aac-422f-d9d0-1a48cc02fed7",
              "eventName": "PRESSED",
              "handlerType": "flow",
              "action": "dummyAction"
            }
          ],
```

In larger projects the action fields are all filled with a reference to the same action.

**Comment by mvladic** [comment]
Fixed.

**Comment by fietser28** [comment]
Works, thank you!
