### ISSUE TITLE
EEZ Flow: Add native checkbox to new global variable dialog

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#305]
Minor UI improvement:
When adding a global variable I would like to have the 'native' checkbox in the new dialog:

![image](https://github.com/eez-open/studio/assets/8796121/ff8f4955-3320-4929-a9a8-ef413ece214d)

Currently I create a variable with the above. Then select the just created variable in the variable list and click the native button. So it just saves a few clicks.

**Comment by mvladic** [comment]
Done.

**Comment by fietser28** [comment]
Works. Thank you.
