### ISSUE TITLE
[LVGL] Add support for LVGL 9.0

### ISSUE THREAD

**Issue by mvladic** [eez-open/studio#311]
For now, add support for all currently implemented widgets and styles to work with LVGL 9.0. It should be possible to choose between versions 8.3 and 9.0 for new and existing projects.

**Comment by mvladic** [comment]
**Important!**

[Online Image Converter](https://lvgl.io/tools/imageconverter) and correspondingly [lv_img_conv library](https://github.com/lvgl/lv_img_conv) do not support LVGL 9.0. Instead, [LVGLImage.py](https://github.com/lvgl/lvgl/blob/master/scripts/LVGLImage.py) python script is used. 

LVGLImage.py script is distributed with the EEZ Studio, but for EEZ Studio to be able to execute this script following requirements must be fulfilled:

1. Python 3 is installed on the system

2. Install `pypng` and `lz4` modules:

      ```
      python3 -m pip install pypng
      python3 -m pip install lz4
      ```

3. Install `pngquant` tool:

      -   Linux (Debian)
      
          ```
          sudo apt install pngquant
          ```
      
      -   Mac
      
          ```
          brew install pngquant
          ```
      
      -   Windows
      
          No action needed, it is distributed with the EEZ Studio.

**Comment by mhaberler** [comment]
Hi,
moving from 8 to 9 as well, and migrated from [PubSub to Observers ](https://github.com/lvgl/lvgl/issues/5419) which work welll

do Observers have any bearing on Studio 8->9 migration?

**Comment by mvladic** [comment]
No, because EEZ Studio and eez-framework don't use PubSub or Observers.

**Comment by liriyao** [comment]
![微信截图_20240724162951](https://github.com/user-attachments/assets/4c13752e-b78a-4430-bc79-341a20ed002c)

**Comment by itarozzi** [comment]
> i have already install pypng and lz4 ,but it still can't build when i have a PNG in the srceen 

In this case seems pypng is well installed, but it encounter some errors in png format. Can you share the png image you are using?

**Comment by liriyao** [comment]
> > i have already install pypng and lz4 ,but it still can't build when i have a PNG in the srceen
> 
> In this case seems pypng is well installed, but it encounter some errors in png format. Can you share the png image you are using?

i just use the wechat srceen shot to make a png like this 
![111](https://github.com/user-attachments/assets/a62605df-b594-4e2f-bffc-7d74230808a4)

**Comment by liriyao** [comment]
> > i have already install pypng and lz4 ,but it still can't build when i have a PNG in the srceen
> 
> In this case seems pypng is well installed, but it encounter some errors in png format. Can you share the png image you are using?

I used another screenshot method windows  screenshot is OK,wechat screenshot don't .Is it a compatibility issue?

**Comment by liriyao** [comment]
![ggggg1](https://github.com/user-attachments/assets/7d734297-9355-4b93-9081-12cb9250e0a3)
fuck the wechat !
