### ISSUE TITLE
LVGL: Allow UTF8 code for custom fonts on Text field

### ISSUE THREAD

**Issue by dolence** [eez-open/studio#318]
I don't know if it is something already implemented but I have a custom font with symbols from Google Fonts/Material Design and I don't know how to reference to individual characters on my label Text field. LVGL handle this using the hex code converted to UTF-8.

![image](https://github.com/eez-open/studio/assets/5223003/49ee1849-89ea-4c0e-8100-7d9ac69d3a3c)

![image](https://github.com/eez-open/studio/assets/5223003/64c6239c-c585-47c4-80e8-d16cef32da12)

![image](https://github.com/eez-open/studio/assets/5223003/051f44d3-ea8a-47b4-aef4-a13ff3472cc2)

**Comment by fietser28** [comment]
Please try: \ue5d2

**Comment by mvladic** [comment]
Also, I'm not sure it will work with literal. If it doesn't work change to expression, i.e.: `"\ue5d2"`

**Comment by dolence** [comment]
> Also, I'm not sure it will work with literal. If it doesn't work change to expression, i.e.: `"\ue5d2"`

This worked! Thank you!

**Comment by mvladic** [comment]
We should support unicode escape (i.e. \ue5d2) also for the literal strings.

**Comment by mvladic** [comment]
Done. Unicode escape (i.e. \ue5d2) is now supported also for the literal strings.

**Comment by claudobahn** [comment]
@mvladic support for unicode escaping appears to have broken w/ 0.23.0 release, specifically with the following commit, I believe: https://github.com/eez-open/studio/commit/c0b2d433393901a2b5259a8970e9d97b881995c6#diff-2818504636f9b20a4b553303c54b052ba7a7d916e47c903132e539ea0e1f919cR100

The chain of `else if` statements probably needs a `else if (ch == "\u")` in addition to `\n`, `\r`, `\t`.

**Comment by mvladic** [comment]
Another user reported the same problem, see #783.
