### ISSUE TITLE
ACTIONS not showing when setting event

### ISSUE THREAD

**Issue by Syrinx98** [eez-open/studio#320]
This is the screenshot of what i see if i try to add an event to a widget, i also tried with other widgets, same problem, the dropdown list seems not to display anything

![Screenshot 2024-02-22 112810](https://github.com/eez-open/studio/assets/71718486/b3f860b7-1b64-4384-9b8e-ffab43ab18de)

**Comment by mvladic** [comment]
Ok, I found what is problem. This Action dropdown is empty because you didn't define any User Action, here:

![image](https://github.com/eez-open/studio/assets/449788/021ef62f-e1e6-486b-a721-4140d1ddee8a)

**Comment by Syrinx98** [comment]
Oh ok, but what is the user action? a function in c the code?

**Comment by mvladic** [comment]
Yes. You created project with EEZ Flow, so your only option for event handler is C function.

**Comment by Syrinx98** [comment]
Perfect, thank you for your speed and your support, and sorry for the silly question (i'm trying to pass from squareline to eez studio, since the recent news).

**Comment by Syrinx98** [comment]
is there any way to change screen with eez studio? without using eez flow?

**Comment by mvladic** [comment]
For example:

```
#include ".../ui/screens.h"

lv_scr_load_anim(objects.main, LV_SCR_LOAD_ANIM_FADE_IN, 200, 0, false);
```
Every page you add will be in objects variable (check `screens.h` header file). Also, every widget with Name property set will be also added to objects variable:

![image](https://github.com/eez-open/studio/assets/449788/462c47d3-e651-46fe-8634-0bf8e50f81f7)

**Comment by Syrinx98** [comment]
Yes, this i know, what i'm saying is: without eez flow there is no possibility to see a screen change in  EEZ studio, right? if i have to try the interface i cannot do that in the program, right?

**Comment by mvladic** [comment]
Yes, you are right.

**Comment by Syrinx98** [comment]
Thank you however, you are very kind!

**Comment by mvladic** [comment]
We concentrated on EEZ Flow as far as Simulator capabilities are concerned. There, interaction with the UI is possible while you are inside Flow. But I think something will need to be done for this scenario when Flow is not used, so that if nothing else, it is possible to switch from screen to screen.
