### ISSUE TITLE
Additional Fonts not rendering correctly with LVGL v9 in EEZ Studio v0.11.0

### ISSUE THREAD

**Issue by janbernrader** [eez-open/studio#328]
When opting for the LVGL v9 version there seems to be an issue with the fonts rendering, see the image attached even though the characters display correctly in the font manager.

![image](https://github.com/eez-open/studio/assets/53154187/20196cca-8b9e-4156-b291-61ecc6faf92f)
![image](https://github.com/eez-open/studio/assets/53154187/3f8eba55-a716-4908-845c-22decf52f1c5)

Furthermore there seem to be some symbols missing with the keyboard widget.
![image](https://github.com/eez-open/studio/assets/53154187/f822ba76-e120-4f41-b559-7320b114cedf)
![image](https://github.com/eez-open/studio/assets/53154187/0ffbd96f-25bd-4813-b113-847bdee49e3c)

**Comment by mvladic** [comment]
For some reason 8 bits per pixel font doesn't work in LVGL 9.0, so choose 4 bits per pixel when creating font.

**Comment by mvladic** [comment]
When adding a font in LVGL project for version 9.0, the default value for bits per pixel will be set to 4 bits.

**Comment by mvladic** [comment]
Done.

**Comment by ats3788** [comment]
Same Problem my keyboard the special icon chars are missing Return backspace move left right and submit and the keyboard is that a special font or what is the problem for this widget oder is LVGL 9.5 the Problem

**Comment by mvladic** [comment]
Your font file doesn't have those special symbols used by the keyboard. The easiest solution is to provide fallback font like this:

<img width="634" height="743" alt="Image" src="https://github.com/user-attachments/assets/e7d0c034-149a-4f9e-8e76-ddbf0e289469" />
