### ISSUE TITLE
Overflow visible flag not under flag dropdown. Documentation states support for overflow visible flag.

### ISSUE THREAD

**Issue by TheMasterCoder007** [eez-open/studio#331]
The documentation for EEZ Studio states support for the overflow visible flag. This flag does not appear to be accessible anywhere in the UI. The best spot to have this would be under the flag dropdown with the rest of the flags.

**Comment by mvladic** [comment]
Support for "Overflow visible" added. 

Please note that it only works in version 8.3. In version 9.0, for unknown reason, it doesn't work. Even though Studio is aware that in version 9.0 `LV_OBJ_FLAG_OVERFLOW_VISIBLE` has changed the value from `(1 << 19)` to `(1 << 20)`.
