### ISSUE TITLE
Support For Windows 7 ?

### ISSUE THREAD

**Issue by KASSIMSAMJI** [eez-open/studio#343]
Here There, I just downloaded the latest version of EEZ Studio (EEZ-Studio-Setup-0.12.0 ) and here what I am getting when trying to run it

![Capture](https://github.com/eez-open/studio/assets/89432773/2a26ac33-85c6-4d3c-a947-5cc1ac2a3b05)

Downgraded to ver: 1.0.0 , still same error

I am using Windows 7 Ultimate with Service Pack 1

Any Help is highly appreciated

**Comment by mvladic** [comment]
EEZ Studio is using [Electron](https://www.electronjs.org/) framework and [Electron from version 23 doesn't support Windows 7](https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice). We are currently using version 28.1.0, so that's the reason why it doesn't work.

**Comment by KASSIMSAMJI** [comment]
Thank you for clarification
