### ISSUE TITLE
[LVGL] Python selection for builds on OS X

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#346]
Following up on a discussion on Discord:

On OS X it is possible to have multiple python versions and / or installations. This causes some confusion/problems when a user runs pip commands from a terminal to install dependencies and eez-studio runs a different python version during the build of LVGL when converting images.

This happens when a LVGL project has images that need to be converted to *.h/*.c files.

The python packages from python.org extend the PATH inside the users .zprofile file and not system wide. When starting studio from a zsh shell (npm start) this is not a problem. But starting studio from the UI (e.g. click on the application icon) the system python is used.

There are a few solutions to this problem:
- add a way for the user to select the python executable/path
- run the python executable inside a zsh shell that sources .zprofile before starting python (e.g. a login shell).
- ?

**Comment by mvladic** [comment]
> add a way for the user to select the python executable/path

In the "Home - Settings", added option to set python path:

![image](https://github.com/user-attachments/assets/84f157cf-797e-4f2b-9539-b171bcef9c93)
