### ISSUE TITLE
LVGL Meter Widget without name causes exception if has expression based needle

### ISSUE THREAD

**Issue by Luke-Shepp** [eez-open/studio#350]
In a new LVGL project, create a float variable, lets say "X". Add a meter widget to the page, and add a needle line to the widget with the value of "X" Variable.

When trying to build, this fails with exception:

<img width="822" alt="Screenshot 2024-04-22 at 22 21 06" src="https://github.com/eez-open/studio/assets/35956374/2d3597bf-c04e-46f8-8252-529fa8b3221a">

This can be resolved by adding a "name" to the meter widget. 

It looks like, `isAccessibleFromSourceCode` is false for a widget in this state, which means the object doesn't make it into `identifiersMap` (see `LVGLIdentifiers::enumIdentifiers`) so building the LVGL code for a child of this widget (the needle line) fails.

I suspect it just needs validation to ensure a name is set? 😃

**Comment by mvladic** [comment]
This should be fixed now.

**Comment by Luke-Shepp** [comment]
Yeah that's got it - thank you 😁
