### ISSUE TITLE
dashboard project: Not mandatory to connect the instrument

### ISSUE THREAD

**Issue by dong-king** [eez-open/studio#352]
In version 0.12.0, when I open a  dashboard project, eez-studio forces me to connect the instrument, otherwise I cannot enter the debug interface.
Is it possible to provide an option to enter the dashboard project interface without connecting the instrument?

By the way, In version 0.12.0， View->Externsion Manager and View->Settings are not working.

**Comment by mvladic** [comment]
> In version 0.12.0, when I open a dashboard project, eez-studio forces me to connect the instrument, otherwise I cannot enter the debug interface.
> Is it possible to provide an option to enter the dashboard project interface without connecting the instrument?

Only for variables marked as "Persistent", Studio will ask to connect to the instrument before starting a dashboard. So, if you don't want this you can uncheck this option.

![image](https://github.com/eez-open/studio/assets/449788/9b0b1fbf-6f0d-4166-81f2-08622fee4aee)

> By the way, In version 0.12.0， View->Externsion Manager and View->Settings are not working.

Thanks, will be fixed.

**Comment by mvladic** [comment]
BTW you can manually open select instrument dialog at any time with the SelectInstrument action component:

![image](https://github.com/eez-open/studio/assets/449788/5d799fb5-a2fd-4f1e-ba03-26df35b5c7df)

**Comment by mvladic** [comment]
> By the way, In version 0.12.0， View->Externsion Manager and View->Settings are not working.

Fixed.
