### ISSUE TITLE
Workbench panels not consistent with other panels

### ISSUE THREAD

**Issue by mvladic** [eez-open/studio#36]
Make workbench panels consistent with other panels (like panels in instrument view and chart view).

Workbench panels:

![image](https://user-images.githubusercontent.com/449788/44904862-a985cb80-ad10-11e8-8b08-7065e21c00a1.png)

Instrument view panels:

![image](https://user-images.githubusercontent.com/449788/44904882-b7d3e780-ad10-11e8-9baa-ecd1b0189e49.png)

**Comment by prasimix** [comment]
Fixed
