### ISSUE TITLE
Possible bugs in importing project process

### ISSUE THREAD

**Issue by glt248** [eez-open/studio#360]
Hello,
When you import 2 instances of a same project :
![image](https://github.com/eez-open/studio/assets/74414695/56139415-42e9-4636-bd31-4406e53d9656)

We can see widgets for the two instances : 
![image](https://github.com/eez-open/studio/assets/74414695/996da2f8-6e42-4ca4-bf80-803a8f55866c)

But instances global variables are not distinct : 
![image](https://github.com/eez-open/studio/assets/74414695/8055a730-538e-482d-bb26-05396a027652)

So if I increment on variable, the two have the same value. I can't use two instances of the same project.

**Comment by mvladic** [comment]
Can you explain the purpose of importing the same project twice?

**Comment by glt248** [comment]
I'm using project to create a front end User Widgets and some User Actions in order to communicate with a DC/DC converter. So that is a under projet.

In a main project, I'm importing two instances of this controller because I'm using 2 DC/DC in a test bench...

**Comment by glt248** [comment]
Ok, thank you for this reply, I will have a look on your proposal.
