### ISSUE TITLE
Add github discussions for general queries or help requests

### ISSUE THREAD

**Issue by DrKropp** [eez-open/studio#362]
First, let me just say that this project is fantastic, and I appreciate all the development that is going into producing an alternative to SquareLine studio now that they are parting ways with the LVGL project. Using this software will definitely result in some hardware sales next time I am in the market.

I have just started using EEZ Studio to develop an LVGL GUI for a project based on the M5Stack M5Dial. I am completely new to GUI development or LVGL, and only have some limited experience with Arduino programming in general.

I have some questions about moving the developed code into VSCode/PlatformIO to integrate with the rest of the project but I don't know that opening an issue is the best place to ask. You should think about enabling the github discussion feature to provide a space for more general help queries that are not related to bugs or other issues.

**Comment by goran-mahovlic** [comment]
Hi @DrKropp 

it would be hard to track all places for discussion, they already have Discord:  https://discord.gg/CRTZ863vSz

so feel free to join in.
