### ISSUE TITLE
[LVGL] Circular display

### ISSUE THREAD

**Issue by LazaroFilm** [eez-open/studio#363]
I would love to see an option for circular displays. I'm using [this module](https://www.waveshare.com/wiki/RP2040-Touch-LCD-1.28) with LVGL. To visualize the circular display I have to fidget with a temporary overlayed round shape as mask. It would be great to have an option to display a circular mask over the display to get a better and faster preview of the final screen.

**Comment by mvladic** [comment]
Something like this?

![image](https://github.com/eez-open/studio/assets/449788/af850148-5aa4-4977-9d27-62bb5021c52f)

**Comment by LazaroFilm** [comment]
Yes!!! Exactly like this!!

**Comment by mvladic** [comment]
Circular display option has been added in Settings:

![image](https://github.com/eez-open/studio/assets/449788/5d80455e-743e-4950-9af5-326305a7c1d3)

**Comment by prasimix** [comment]
Fixed
