### ISSUE TITLE
[LVGL] Needle image with hyphen in name incorrectly handled

### ISSUE THREAD

**Issue by Luke-Shepp** [eez-open/studio#364]
I have a gauge, with a needle image and the needle image is called `rpm-needle`, seen below:

<img width="667" alt="Screenshot 2024-05-11 at 17 49 35" src="https://github.com/eez-open/studio/assets/35956374/c01d0b3e-b207-4916-96fa-444a16a69d7a">

<img width="328" alt="Screenshot 2024-05-11 at 17 49 43" src="https://github.com/eez-open/studio/assets/35956374/b534262d-a8b8-4fa5-8e22-6ac2ea58a8d1">

This however generates invalid code as it does not replace the `-` with `_` when building `create_screen_main`:

<img width="864" alt="Screenshot 2024-05-11 at 17 49 31" src="https://github.com/eez-open/studio/assets/35956374/9f7b9758-500f-49cd-8aa6-5f480ae4d412">

---

Various other places do correctly make the substitution, such as images.c and the image-specific .c file - it seems to be just this location that does not

**Comment by prasimix** [comment]
Fixed
