### ISSUE TITLE
No label in Button

### ISSUE THREAD

**Issue by aquananu** [eez-open/studio#370]
after adding a Button to the page, on clicking it the properties in general tab show only name, no field for label is there.
![image](https://github.com/eez-open/studio/assets/93096176/0a1b259d-d9b9-47e2-b29f-15a1d3f564e1)

The specific properties option is not being show, i m using the software on windows 10

i am using 
![image](https://github.com/eez-open/studio/assets/93096176/732997f1-a22b-410a-87d0-d077e08ea841)

Also advise how to switch page to another on click, i have added event - Pressed - Flow and added Animate from GUI connected it to the button and now in to what to be selected

**Comment by mvladic** [comment]
These types of questions are better to be asked on our [Discord](https://discord.gg/dhYMnCB) server.
