### ISSUE TITLE
[Dashboard] New widget for tabular display of data

### ISSUE THREAD

**Issue by mvladic** [eez-open/studio#379]
Add new widget for tabular display of data from the database or imported files.

Table cells should be able to contain:

- [x] simple label
- [x] tree label
- [x] progress
- [x] checkbox or 
- [x] image. 

Enable:

- [x] sorting by columns
- [x] pagination
- [x] search
- [x] export to HTML
- [x] export to PDF (includes #12)
- [x] export to CSV.

Allow inserting table into instrument history.

More tasks:

- [x] Build formatter property for enum types
- [x] Sync columns with structure and enum types

**Comment by fietser28** [comment]
I would like to have  a button to 'load column from data': If I specify a structure type variable in the data field pressing this button will disable auto column and defines all the columns based on the elements of the structure pointed to in the data field. This allows to quickly make an editor/display for existing data structures.

Manually performing this action is very cumbersome, also because I don't know how to display both the definition of the structure and the definition of the table column at the same time. So for each element I have to switch in UI.

**Comment by fietser28** [comment]
The auto column mode doesn't resolve enumerations. It shows numbers.

**Comment by fietser28** [comment]
Using a array of struct (in screenshots: profiles is array of  batteryProfile struct) as data input: If the struct contains a double the value displayed is incorrect, both when using plaintext and money (which appears to the number formatting type):

<img width="482" alt="image" src="https://github.com/eez-open/studio/assets/8796121/c00f3bd6-c281-4680-813b-d0d92aa375a9">
<img width="278" alt="image" src="https://github.com/eez-open/studio/assets/8796121/2c49d607-4662-43fa-843c-a7e3e3dc0060">
<img width="449" alt="image" src="https://github.com/eez-open/studio/assets/8796121/f8f6ca51-c19d-4ba8-9a2d-eb2587f03afe">
<img width="790" alt="image" src="https://github.com/eez-open/studio/assets/8796121/1dd0a800-28fc-42d0-8039-99c0a4cc8ea5">

I think this is a very important use case.

**Comment by mvladic** [comment]
> The auto column mode doesn't resolve enumerations. It shows numbers.

Auto column is implemented by the Tabulator library. But, it makes sense if input data comes from `array:struct:...` to override tabulator implementation since in this case Studio knows better.

**Comment by fietser28** [comment]
> > The auto column mode doesn't resolve enumerations. It shows numbers.
> 
> Auto column is implemented by the Tabulator library. But, it makes sense if input data comes from `array:struct:...` to override tabulator implementation since in this case Studio knows better.

I agree but think the user knows even better but it is a lot of work to manually define all the columns that represent the struct elements. If there is a button that generates the column definitions with some sensible defaults, the users can easily customize the column afterwards. Pressing the button is a 1 time action.

**Comment by mvladic** [comment]
Sure, both features should be added.

**Comment by fietser28** [comment]
> Using a array of struct (in screenshots: profiles is array of batteryProfile struct) as data input: If the struct contains a double the value displayed is incorrect, both when using plaintext and money (which appears to the number formatting type):

Juist noticed this problem is also present in the JSON Stringify action. So probably this is a more generic issue regarding internal struct -> json conversion.

**Comment by fietser28** [comment]
> > Using a array of struct (in screenshots: profiles is array of batteryProfile struct) as data input: If the struct contains a double the value displayed is incorrect, both when using plaintext and money (which appears to the number formatting type):
> 
> Juist noticed this problem is also present in the JSON Stringify action. So probably this is a more generic issue regarding internal struct -> json conversion:
> 

Did some more test. It appears only Double type is not working, other variable types work fine:
<img width="917" alt="image" src="https://github.com/eez-open/studio/assets/8796121/06ecca48-5387-4ecb-adf1-09bb0705d0df">

<img width="1177" alt="image" src="https://github.com/eez-open/studio/assets/8796121/3089bae2-e06f-4bf9-aad1-df21f9d0975a">

**Comment by mvladic** [comment]
I found what is the problem with doubles in struct. It only appears when struct is defined through "Default value". If you make a struct with `Flow.makeValue("struct:mystruct", { ... })` it will work fine. The root cause for the problem is that doubles are not 8 byte aligned. I will commit the fix soon.

**Comment by mvladic** [comment]
Fix for doubles commited.

**Comment by fietser28** [comment]
It works for all my use cases.

**Comment by mvladic** [comment]
I added command "Build From Structure Definition":

![image](https://github.com/eez-open/studio/assets/449788/786b9771-6843-40d5-a29d-14748342d994)

Also, when "Auto columns" is enabled we will override auto columns feature from Tabulator in case of table data is of structure type and infer columns info from Structure definition.

For now, only Title and Field is inferred. In the future we will try to infer other Column properties, please be free to suggest it.

**Comment by mvladic** [comment]
I forgot enum types, we should build formatter property from that.

**Comment by fietser28** [comment]
This is how I'm now manually configured enum (still working out the exact settings for my case):
<img width="566" alt="image" src="https://github.com/eez-open/studio/assets/8796121/b9f2be9a-7d97-4087-a8ac-43170152169a">

I think the generation/sync of the parameter list is important/convenient.

**Comment by mvladic** [comment]
It doesn't sync for now. For sync we should have a new property:

Auto columns         [ ]
Sync columns with structure definition: [x] ____my_struct [V]

**Comment by mvladic** [comment]
This is required because if you build from structure and changed some column property you don't want sync to overwrite it. So you are all for sync or no sync.

**Comment by fietser28** [comment]
Working on my example I'm hitting a limitation when working with selections. Selections are nice to allow for the deletion, duplication, etc of rows in my use case:

<img width="1218" alt="image" src="https://github.com/eez-open/studio/assets/8796121/75fb9ca5-04a9-4f45-b49b-bd897041d690">

Please add 'row selected' and 'row deselected' events to the widget. The event should return the index number of the index of the row selected (not the displayed order but the index of the data array given to the tablulator).
See [https://tabulator.info/docs/6.2/events#select](https://tabulator.info/docs/6.2/events#select) 

These events will allow me to implement a 'delete row' , 'duplicate row' and a 'use row' functions.

**Comment by mvladic** [comment]
I have added ON_ROW_SELECTED and ON_ROW_DESELECTED events. Both events outputs json value:

```
{
  index: number, // 0-based index in table data
  position: number // 1-based position in displayed rows
}
```

You will use `.index`.

**Comment by mvladic** [comment]
Also, columns properties for enum types are also generated:

![image](https://github.com/eez-open/studio/assets/449788/98f56dfc-6313-4fe1-8753-f2bf441384b4)

But, this is still work in progress.

**Comment by prasimix** [comment]
Fixed
