### ISSUE TITLE
Workbench goes blank when USB Instrument Interface has problem

### ISSUE THREAD

**Issue by sujitth** [eez-open/studio#38]
Hi,
My EEZ Studio installation(Win7x64) got messed up when I tried to change the Rigol DS1054z Oscilloscope interface from Ethernet to USBTMC, workbench screen gone blank with an empty white window.
Uninstalled and reinstalled with Appdata folder contains only the storage.db, The scope were showing with a question mark only and when clicked again blank screen appears.
Put back the backup Appdata folder and created a new scope instrument with interface USBTMC and it gives an error - "LIBUSB_ERROR_NOT_SUPPORTED"

Ctrl+R brings back the window, but nothing can be done with that instrument, I have to create another one for usage.
![eezstudio_2018-11-30_13-20-08](https://user-images.githubusercontent.com/6084883/49297105-f7f96080-f4df-11e8-8d77-617c1252c67f.png)
![eezstudio_2018-11-30_16-03-12](https://user-images.githubusercontent.com/6084883/49297144-10697b00-f4e0-11e8-9404-dd31ca0e4aaa.png)

The problematic Instrument icon came back after a couple of restart and I could browse the data(blank screen appears,by reloading it) but couldn't change the interface back to Ethernet, I am using the newly created instrument for regular usage now.

and why I need to generate USB driver for windows? The scope is working fine with the Rigol Ultra Scope software on USB.
![ultra_sigma_2018-11-30_21-13-38](https://user-images.githubusercontent.com/6084883/49299543-f9c62280-f4e5-11e8-8bf3-f651cf37c8ef.png)

**Comment by prasimix** [comment]
Please check that with the latest release. Many things were changed since then.
> why I need to generate USB driver for windows? The scope is working fine with the Rigol Ultra Scope software on USB.

Ultra sigma is using USB-TMC via IVI/VISA driver that's why you don't need to install USB driver.
