### ISSUE TITLE
[Dashboard] automatic json to array of struct conversion results in instability

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#391]
**Describe the bug**
Using the tabulator with an array of struct: When I update the array if something is changed/editted in tabulator everything seems to work fine, but after that a Array.append( array, ...) throws an error the arrays is not an array.

**To Reproduce**
1. Edit a value in the table, press enter to store
2. Select a row
3. Press 'duplicate row'

**Expected behavior**
Duplicate keeps working after an edit. 
If Step 1 is omitted everything works fine. I suspect the action in step 1 causes some kind of corruption due to the conversion of json to array of struct.

**Screenshots**
Step 1 causes the following action to execute:
<img width="751" alt="image" src="https://github.com/eez-open/studio/assets/8796121/bfe6873a-0b14-439f-97b1-88c5067bece3">

Step 2 executes:
<img width="368" alt="image" src="https://github.com/eez-open/studio/assets/8796121/e48e10a1-4237-4ad0-9371-d8360e30fc36">

Step 3 executes:
<img width="515" alt="image" src="https://github.com/eez-open/studio/assets/8796121/251efc9e-363a-47b3-a49f-fe83139b0165">

Error:
<img width="958" alt="image" src="https://github.com/eez-open/studio/assets/8796121/25925b28-5a8d-423e-a792-bf38365b5ee6">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 14.2.1

**Comment by fietser28** [comment]
[BatteryDischarge.eez-dashboard.zip](https://github.com/user-attachments/files/15522777/BatteryDischarge.eez-dashboard.zip)

The dashboard to test with.

**Comment by mvladic** [comment]
> The dashboard to test with. 

There is no eez-project in the zip file.

**Comment by fietser28** [comment]
[BatteryDischarge.eez-project.zip](https://github.com/user-attachments/files/15522897/BatteryDischarge.eez-project.zip)
Retry...

**Comment by fietser28** [comment]
Also noticed the same error happens after loading a file. You can easily create a json by saving the default values to a file first.

**Comment by mvladic** [comment]
Fixed.

**Comment by fietser28** [comment]
Thanks!
