### ISSUE TITLE
[LVGL] Allow configuring chart axes, data

### ISSUE THREAD

**Issue by tylercamp** [eez-open/studio#392]
**Is your feature request related to a problem? Please describe.**
Coming from SLS I noticed that the LVGL Chart widget doesn't exactly fit within its intended bounds, so for faster iteration times I'd like to be able to see the final rendered widget with some data in EEZ Studio and make appropriate tweaks.

**Describe the solution you'd like**
I'd like a "Specific" section for LVGL charts which would let me specify data and configure axes.

**Describe alternatives you've considered**
I considered switching to EEZ-GUI, which does allow for this configuration, but I plan to use the Arc widget for data display which doesn't quite have a good analog in EEZ-GUI. (The "Gauge" widget doesn't seem to have an option to extend it beyond the 180-degree arc, and there aren't any options to remove the tick markers.)

**Comment by mvladic** [comment]
Same as #482.
