### ISSUE TITLE
[LVGL] LVGL v9 keyboard events are scrambled

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#393]
**Describe the bug**
The keyboard widget in v9 doesn't send a READY event, only a cancel event when READY is pressed. Cancel doesn't create an event.

**To Reproduce**
Run the attached project in simulator in debug mode.
Press the OK button: a cancel even is generated.
Press the cancel button: no event is generated.

**Expected behavior**
Same as in v8.3

** LVGL version (if used)**
V9 is not working. Changing the project to v8.3 it works.

[lvgl-with-flow-tests.eez-project.zip](https://github.com/user-attachments/files/15524902/lvgl-with-flow-tests.eez-project.zip)

**Comment by mvladic** [comment]
Fixed.
