### ISSUE TITLE
Add search field to expression builder

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#400]
**Is your feature request related to a problem? Please describe.**
No, just UI enhancement

**Describe the solution you'd like**
In the expression builder I would like to have a search field. This search field filters the options shown by the expression builder. This is nice because sometimes the list in the expression builder are long, see screenshot below. The filter in the variable tab shown in the background works like a charm, so would also like to have this in the expression builder.

<img width="1502" alt="image" src="https://github.com/eez-open/studio/assets/8796121/f2ebd806-004a-4c8e-a2f1-8cc507919d72">

**Comment by fietser28** [comment]
Small addition: Maybe also add a sync option to the search field just like in the SCPI terminal: If you start typing in the edit field a search is automatically performed.

**Comment by mvladic** [comment]
Implemented.

![image](https://github.com/eez-open/studio/assets/449788/fe2ad846-9480-4be3-9ee6-831cfeb013b2)

> Small addition: Maybe also add a sync option to the search field just like in the SCPI terminal: If you start typing in the edit field a search is automatically performed.

I haven't done this yet. It makes more sense for SCPI commands, since there is a help page associated with the command. Until we can do the same for the expression parts, I think there is no point to add sync option.

**Comment by fietser28** [comment]
> > Small addition: Maybe also add a sync option to the search field just like in the SCPI terminal: If you start typing in the edit field a search is automatically performed.
> 
> I haven't done this yet. It makes more sense for SCPI commands, since there is a help page associated with the command. Until we can do the same for the expression parts, I think there is no point to add sync option.

I agree.

It is working fine. Thank you.
