### ISSUE TITLE
[LVGL] Support scrollbar mode and scroll direction

### ISSUE THREAD

**Issue by mverch67** [eez-open/studio#421]
I didn't find a way to configure the scrollbar in lvgl projects.

```
- LV_SCROLLBAR_MODE_OFF : Never show the scrollbars
- LV_SCROLLBAR_MODE_ON: Always show the scrollbars
- LV_SCROLLBAR_MODE_ACTIVE: Show scroll bars while an object is being scrolled
- LV_SCROLLBAR_MODE_AUTO: Show scroll bars when the content is large enough to be scrolled
```

Reference:
https://docs.lvgl.io/master/overview/scroll.html#mode

**Comment by mvladic** [comment]
Implemented.

In the Flags section there are two new properties:

![image](https://github.com/eez-open/studio/assets/449788/cd8c13ad-bf6b-457c-99f4-3c8a9e45ba25)

If left empty then no call to `lv_obj_set_scrollbar_mode` and `lv_obj_set_scroll_dir` will be generated - this is default when new widget is added to the screen.

**Comment by mverch67** [comment]
Works nicely! Thanks for your great support!
