### ISSUE TITLE
Shown array size in debug Watch panel

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#422]
**Is your feature request related to a problem? Please describe.**
Just a UI request: Show the length of an array in de debug Watch panel:

<img width="439" alt="image" src="https://github.com/eez-open/studio/assets/8796121/a4c3f1dd-f8cc-4673-935e-c58d1b912eec">

**Describe the solution you'd like**
Show the length in the empty Value column of the array.

Often I'm interested if the correct size is allocated (when doing dynamic allocation).

**Comment by mvladic** [comment]
Implemented.

**Comment by fietser28** [comment]
Working fine. Thank you!

**Comment by mvladic** [comment]
I think I have a memory leak in Debug mode. I'm looking into this.
