### ISSUE TITLE
Support Button matrix widget

### ISSUE THREAD

**Issue by mvladic** [eez-open/studio#424]
https://docs.lvgl.io/8.0/widgets/core/btnmatrix.html

**Comment by liriyao** [comment]
Can eez studio set event for every single Button in the btnmatrix?

**Comment by mvladic** [comment]
Use `VALUE_CHANGED` event. This event will send ID, i.e. index of the button pressed:

![image](https://github.com/user-attachments/assets/e1adbf73-909e-4e3b-ba7f-d60d469b0039)

![image](https://github.com/user-attachments/assets/9392f14f-2260-4b33-bda8-34edcae1fd21)

**Comment by liriyao** [comment]
> Use `VALUE_CHANGED` event. This event will send ID, i.e. index of the button pressed:
> 
> ![image](https://private-user-images.githubusercontent.com/449788/351994229-e1adbf73-909e-4e3b-ba7f-d60d469b0039.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTA3NDMsIm5iZiI6MTcyMTg5MDQ0MywicGF0aCI6Ii80NDk3ODgvMzUxOTk0MjI5LWUxYWRiZjczLTkwOWUtNGUzYi1iYTdmLWQ2MGQ0NjliMDAzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwNjU0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDA5NjY3YzVlOTc2ZjEyOWZiYTBiYjdhYzEyMzliMmExYzcyMTY1NTJhMmY3MDkwMDc4MTVhMWMwODlhMjE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gcryun11P9EkHwASoDzFqz4F8Af7WT-da1sp0ZPM_PY)
> 
> ![image](https://private-user-images.githubusercontent.com/449788/351995221-9392f14f-2260-4b33-bda8-34edcae1fd21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTA3NDMsIm5iZiI6MTcyMTg5MDQ0MywicGF0aCI6Ii80NDk3ODgvMzUxOTk1MjIxLTkzOTJmMTRmLTIyNjAtNGIzMy1iZGE4LTM0ZWRjYWUxZmQyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwNjU0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzIxNDkwOThjMTMyMDk3ZGViYmNlMjQwYjRlMDA4OGVjOGY5YWQwZDY1ZmQ3ZjdmMzU1NGNlYWJkZDJiZWZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qlRAgyBBgwvoTCtfxj3ccwks3dB6xMCf5Tfru72wJCE)

ths
