### ISSUE TITLE
Error Generating Bitmap in LVGL V9

### ISSUE THREAD

**Issue by elmonic** [eez-open/studio#425]
hi
I'm using eez studio for LVGL v.9 project.
all pictures used in app not generated.
![20240624_102255](https://github.com/eez-open/studio/assets/37238303/19750a3f-d42f-481b-8c76-6331fc0b8a80)
thanks
eez studio V0.14.0

**Comment by mvladic** [comment]
https://github.com/eez-open/studio/issues/311#issuecomment-1986932418

**Comment by mvladic** [comment]
> I am using Windows and according to your description, the entire conversion operation is performed by the software itself.

No action is required only for the point no. 3, you still need to do points no. 1 (install python 3) and 2 (install pypng and lz4 python modules).

**Comment by elmonic** [comment]
Hello, thank you for your support.
I had not paid attention to the titles.
The problem was solved.

**Comment by mvladic** [comment]
On the Mac, there is some additional issues. Here is what description from the [Discord](https://discord.com/channels/511131497801973761/511133306675396629/1230097334826958889)

> Ok, I think I found the problem: Try starting studio by going into the /Application/EEZ-Studio folder (right-click on the application and select 'Show package contents'), browse to Contents -> MacOS. Inside this directory there is a Unix executable called 'EEZ Studio'. Right click this one and select open. 
> This starts EEZ Studio and probably your build will work now.
>
> Why does this work: the python package adds the path to python in the .zprofile file which is not read if you start the application in the regular way.
