### ISSUE TITLE
[LVGL] Add the LVGL container object

### ISSUE THREAD

**Issue by Jvsjvs** [eez-open/studio#429]
Currently EEZ Studio does not provide the Container object in the V9 LVGL code generation.

Please add this standard LVGL component as it is used frequently to create a hierarchy in the UI layout structure. In order to migrate from SquareLine Studio to EEZ Studio the missing components are required.

**Comment by mvladic** [comment]
Already implemented:

![image](https://github.com/user-attachments/assets/30dc6432-2b46-4a8c-88e8-bbd3daea72a2)
