### ISSUE TITLE
[Dashboard] how to watch a global variable?

### ISSUE THREAD

**Issue by dong-king** [eez-open/studio#431]
I use `watch` action as shown below(changed from `SerialPort` exmaple), but it didnt work.
1. add a user action:  watchSerial. it watchs serial connection status.
![image](https://github.com/eez-open/studio/assets/58795990/d2a843ca-c612-4425-bff4-65204be62195)

2. add `watchSerial` to page
![image](https://github.com/eez-open/studio/assets/58795990/9362bf9e-01cc-4f3f-8c59-81a097d04c32)

Test:
when i click `Connect` button, no output is seen in the logs area.
can `watch` action be used in a user action?

**Comment by mvladic** [comment]
Watch action alone will not keep user action running, you can add Delay action like this:

![image](https://github.com/eez-open/studio/assets/449788/fd739a6f-d4da-4db8-84c4-e01c2feec04d)
