### ISSUE TITLE
[Dashboard] SetVariable action will cause the original variable to be modified

### ISSUE THREAD

**Issue by dong-king** [eez-open/studio#432]
**Describe the bug**
```
struct TREE_NODE:
{
    key: string,
    title: string,
    info: string
}
```
`originalData` and `treeData` are array:struct:TREE_NODE
Use variable `originalData` to initialize `treeData` with `SetVairable` action.
When the button is clicked, the info field of `treeData` is modified, and the info field of  `originalData` is modified too.

**Expected behavior**
`originalData` need remain unchanged.

**Screenshots**
![image](https://github.com/eez-open/studio/assets/58795990/b0e72c5b-6dd4-4014-948f-7b154380bdef)

before clicking button:
![image](https://github.com/eez-open/studio/assets/58795990/680459fa-1e56-48bd-9b9d-1ae0cb83215f)

after clicking button:
![image](https://github.com/eez-open/studio/assets/58795990/21cfe988-ea9c-4814-9481-f18247d13873)

**Desktop (please complete the following information):**
 - OS: win10
 - eez-studio v0.13.0

**Comment by mvladic** [comment]
If `Array.clone` is not used then both `treeData` and `originalData` variables points to the same data.
