### ISSUE TITLE
[lvgl] gesture event LV_EVENT_GESTURE missing

### ISSUE THREAD

**Issue by lehoangphuc86** [eez-open/studio#436]
Hi Team, 

I am new to this tool. While designing our GUI, it seems we are missing the LV_EVENT_GESTURE event on the event dropdown.
May I know how to detect the gesture event like the lvgl natively supports?

Appreciate your response.
Version: 0.14.2
LVGL: 8.3

Peter

**Comment by mvladic** [comment]
Done. Will be released in EEZ Studio version 0.15.0.

Here is an example project:

[test_gesture_event.zip](https://github.com/user-attachments/files/16116789/test_gesture_event.zip)

![gesture](https://github.com/eez-open/studio/assets/449788/e59f4ca1-192f-45eb-8cb7-4b65249334b2)

**Comment by mvladic** [comment]
To receive Gesture event, "Gesture bubble" flag must be unchecked:

![image](https://github.com/eez-open/studio/assets/449788/3a516f03-8ae2-499c-a86c-74a8a3e9489d)

**Comment by lehoangphuc86** [comment]
Thanks for your quick action. It means there is no option to get the gesture event in 0.14.2 right?
Also, I am working in lvgl + eez without flow. In my screen, I only have the dropdown to select the possible events.

![image](https://github.com/eez-open/studio/assets/43288128/11df0523-f607-4de2-9a35-2ec36a3a342e)

**Comment by mvladic** [comment]
> It means there is no option to get the gesture event in 0.14.2 right?

Correct.

**Comment by mvladic** [comment]
> Also, I am working in lvgl + eez without flow. In my screen, I only have the dropdown to select the possible events.

You can always add event handler from the code.

**Comment by lehoangphuc86** [comment]
> > Also, I am working in lvgl + eez without flow. In my screen, I only have the dropdown to select the possible events.
> 
> You can always add event handler from the code.

It means, I need to modify the generated source code to handle the LV_EVENT_GESTURE event right?
I prefer to not touching the generated source code, because any time I modify something on the GUI, I will re-generate and it will override my modification. 
Currently, I am separating the generated source and the app implementation.
If you confirm the same, in the next version, I think it is better to add all supported events into the dropdown on the studio or let user add their customize event name .

Thank you. I will close the issue after your confirmation.

**Comment by lehoangphuc86** [comment]
Thank you for the clarification. Please close this case.
