### ISSUE TITLE
[lvgl] exported lvgl code (lv_arc) doesn't respect custom value range

### ISSUE THREAD

**Issue by jcuypers** [eez-open/studio#443]
Custom value range works correctly in run mode, but isn't exported in code

Defining and simulating (running) an arc with a custom range in studio works as expected. however while exporting the range statement is omitted, making it behave like a standard 0-100 scale.

Please implement the correct scale on export
 ` lv_arc_set_range(obj, <start>, <end>);`

tested with latest codebase

**Comment by mvladic** [comment]
Fixed.

**Comment by jcuypers** [comment]
tested. works as expected
