### ISSUE TITLE
[Dashboard] An exception occurred while copying a docking manager container

### ISSUE THREAD

**Issue by dong-king** [eez-open/studio#452]
**Describe the bug**
![image](https://github.com/user-attachments/assets/c525a2e7-5f1c-4898-9359-892fe0a791a8)

1. right click on the docking manager container;
2.  click `Copy` or `Duplicate`. 

The error message is as follows:
![image](https://github.com/user-attachments/assets/96066c1b-7083-4cb9-a59f-758b66fa329d)
 

**Desktop (please complete the following information):**
 - OS: Windows10
 - Version eez-studio V0.14.2

**Comment by mvladic** [comment]
Fixed.
