### ISSUE TITLE
eez delete me all flow, also local var, global var define as NATIVE

### ISSUE THREAD

**Issue by petrubuciu** [eez-open/studio#453]
**Describe the bug**
when i open the eez studio v0.14.2 to continue my work, i saw that i have 50 error in checks. also when i looked at my global vars i saw that are [NATIVE]name_of _var but all globals was not define as native. also i can't find any flow that i have created. and local vars on each screen created deleted i think because in checks tells me that local var doesn't exists

**To Reproduce**
1. just fresh open the eez studio

**Expected behavior**

**Screenshots**
<img width="649" alt="image" src="https://github.com/user-attachments/assets/f25ca94e-ef1e-4e65-9613-fb0a0430dd70">

**Desktop (please complete the following information):**
 - OS: MacOS (arm version M1 max)
 - Version Sonoma 14.5

** LVGL version 8.3**

**Additional context**
i dont know if i was doing something wrong, yesterday i change from lvgl 8.3 to 9 and then i export(build) also then i switched back to 8.3. but even after that i switched back to 8.3 i was able to export(build) the project with no errors. but today was not working at all

**Comment by mvladic** [comment]
Is it possible that you unchecked "Flow supprort" switch?

![image](https://github.com/user-attachments/assets/ecbbe9d3-c3ff-4a0f-aaa4-5773de9fc940)

**Comment by petrubuciu** [comment]
is active, also export export eez flow engine

**Comment by mvladic** [comment]
This could happen if at one point flow support is disabled and then again enabled (unfortunately, if you saved your project after this all your flow specific stuff will be lost). Indication for this is:

> ... when i looked at my global vars i saw that are [NATIVE]name_of _var but all globals was not define as native" ...

When you disable flow support all your variables will become native.

**Comment by mvladic** [comment]
Of course, I don't want to claim that you did something like this. I'm just trying to figure out what could have happened, i.e. in which scenario something like that (all global variables becoming native) could happen.

**Comment by petrubuciu** [comment]
i dont remember if i diesable flow support. its posible. there is a posibile solutie to get back? or i need to start again the flows? :(

**Comment by mvladic** [comment]
If you saved your project after you disabled flow support, all the flow specific parts of the project are lost.

**Comment by mvladic** [comment]
I'm really sorry if your work has been lost 😒I hope it will not be too much of the effort to create it again, maybe this time will be even better. I created an issue #454 so that user is at least alerted of the irreversibility of this action.
