### ISSUE TITLE
[LVGL] Allow enabling default dark theme in editor and generated files

### ISSUE THREAD

**Issue by tylercamp** [eez-open/studio#456]
**Is your feature request related to a problem? Please describe.**
LVGL offers a default dark theme which I'd like to use.

**Describe the solution you'd like**
I'd like a checkbox in the project settings page for whether to use light or dark theme for the project. It would modify `screens.c` code generation and apply to widgets shown within EEZ Studio editor

**Describe alternatives you've considered**
I'm currently applying a new theme with dark mode after the init call to EEZ Studio's generated code, but I'd like to manage the setting and see a preview of those changes directly in EEZ Studio.

---

The code-gen update would be easy but I'm not sure about updating widget styling within EEZ Studio's preview. I see a reference to a [wasm](https://github.com/eez-open/studio/blob/8fa02efb7f30b6f203bed2bdb15cd6e325402a5d/packages/project-editor/lvgl/widgets/Button.tsx#L88) wrapper util, so I assume there's some sort of LVGL web binding being used, but I can't tell how the [lvgl_runtime_*](https://github.com/eez-open/studio/tree/master/packages/project-editor/flow/runtime) files are being generated

(If it's using a proper LVGL API binding then updating EEZ UI for dark mode would probably be easy too, but I can't tell whether that's the case)

**Comment by mvladic** [comment]
Implemented.

![image](https://github.com/user-attachments/assets/20c29345-267f-44d8-8fa0-e6700b0a3474)

**Comment by gwiethaus** [comment]
First, please excuse my English

In the new version EEZ Studio 0.16.0 I enabled the "dark theme" and it only changed the development screen. The editor continues with the default white theme.

**Comment by mvladic** [comment]
For the EEZ Studio you can select dark theme here:

![image](https://github.com/user-attachments/assets/9d709ba5-f343-470f-88f0-51fd69d9de92)

**Comment by gwiethaus** [comment]
Thanks for the tip.
I created a new database. However, I discovered that I can't access the bottom of the screen. I think the scroll bar to reach the rest of the features is missing. I marked it in red as far as I can see on the screen. Remember that I'm using a laptop.

![Screen Setting](https://github.com/user-attachments/assets/de528130-1c24-4edf-82fc-07efdc790358)

**Comment by gwiethaus** [comment]
> For the EEZ Studio you can select dark theme here:
> 
> ![image](https://private-user-images.githubusercontent.com/449788/363695976-9d709ba5-f343-470f-88f0-51fd69d9de92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyODM0NTgsIm5iZiI6MTcyNTI4MzE1OCwicGF0aCI6Ii80NDk3ODgvMzYzNjk1OTc2LTlkNzA5YmE1LWYzNDMtNDcwZi04OGYwLTUxZmQ2OWQ5ZGU5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQxMzE5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGMxODk4YTY2Y2Q1OTNiZDVkZWE0ZjNkMTcwODhkOTZiYzczYTJhNzE3MzM2MzNkMmNmNzM1MTg3YjgxMTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h8B6fDGwjZacx6pxrmDIv95m-cq4Muroecgpa_uo2fU)

Thanks for the tip.
I created a new database. However, I discovered that I can't access the bottom of the screen. I think the scroll bar to reach the rest of the features is missing. I marked it in red as far as I can see on the screen. Remember that I'm using a laptop.

![Screen Setting](https://github.com/user-attachments/assets/61e76dc3-8c4d-480d-9796-c2a6929967ad)

**Comment by mvladic** [comment]
Hm, this is bug. Fortunately, you can also select dark theme from the main menu:

![image](https://github.com/user-attachments/assets/2efcf6c6-7fb3-4519-abdf-8ef1e59e0e04)
