### ISSUE TITLE
[LVGL] Add user_data to event callbacks

### ISSUE THREAD

**Issue by itarozzi** [eez-open/studio#457]
**Is your feature request related to a problem? Please describe.**

At the moment does not exists a way to add user_data to a callback button. I  see I can link a button event to an UserAction, but no way to pass user_data to them.

I would like to use same callback for several widgets, but I need to get caller ID or caller data (without using global variables)

**Describe the solution you'd like**

I would like an edit box in the event panel to assign number or variable name or obj reference. This parameter will be passed to lv_obj_add_event_cb() generated by eez-studio.  

**Describe alternatives you've considered**

I'll try to use variables with Flow assignement, but I don't know if the flow is executed before the event call, so I can check the variable value inside the User Action implementation in my C code

**Comment by mvladic** [comment]
Implemented.

It is now possible to specify integer user data:

![image](https://github.com/user-attachments/assets/ce8528ea-e950-4234-8452-707666858c78)
