### ISSUE TITLE
Add event handler for LGVL project

### ISSUE THREAD

**Issue by iryna7** [eez-open/studio#458]
Hi, 
anyone knows...

1. How to Add event handler for LVGL project. just like screen change event.
2.  Can't compile fot the LVGL Flow or GUI project.  it is shows eez/flow/lvgl_api.h missing errors. 

I'm working on the Arduino for ESP32. thanks in advance.

BR
HS

**Comment by mvladic** [comment]
> 1. How to Add event handler for LVGL project. just like screen change event.

There is a "Event handlers" section in widget properties:

![image](https://github.com/user-attachments/assets/03761fb8-e08e-471c-9737-b3b5b3f1191a)

> 2. Can't compile fot the LVGL Flow or GUI project. it is shows eez/flow/lvgl_api.h missing errors.

You need to link with the [eez-framework](https://github.com/eez-open/eez-framework). But, from EEZ Studio version 0.14.1 onwards there is support for generating EEZ Flow engine source code along with other source code, see #385.

For other questions you can also check [Q&A](https://github.com/eez-open/studio/wiki/Q&A) and our [Discord](https://discord.gg/dhYMnCB).
