### ISSUE TITLE
[LVGL] Dropdown add list style

### ISSUE THREAD

**Issue by elmonic** [eez-open/studio#461]
The drop-down list does not have the ability to change the style of the list.
![dropdown](https://github.com/user-attachments/assets/23b1e009-b548-4086-b322-fea764a3ff40)
LVGL v9
EEZ Studio V14.2

**Comment by mvladic** [comment]
You are right, this is currently not possible. It will be supported.

**Comment by mvladic** [comment]
This is now supported. 

Just add Container widget as a child of the Dropdown, it will be named List and you will be able to style it:

![image](https://github.com/user-attachments/assets/deffe8b3-4a95-4ead-9e94-43330cf25c8e)
