### ISSUE TITLE
Add LVGL key definitions to expression builder.

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#469]
**Is your feature request related to a problem? Please describe.**
When using key events from LVGL in flow you have to manually lookup the key codes and hardcode them. 

**Describe the solution you'd like**
Add the LVGL_KEY_* to the expression builder. In the generated code these constants are already present. This is very similar to the LVGL symbols already in the expression builder.

**Describe alternatives you've considered**
Hardcoding the values. You also first have to look them up in LVGL documentation.

**Comment by mvladic** [comment]
Actually, we should add system enumeration type $LVGLKey like we already have $LVGLDir.

**Comment by mvladic** [comment]
![image](https://github.com/user-attachments/assets/5d807158-6f63-441d-8f0e-00f4dfcbb0f7)

**Comment by mvladic** [comment]
Hm, on second thought I don't know why I added System enumeration $LVGLDir when I already have prior case with LVGL.LV_SYMBOL_....

**Comment by fietser28** [comment]
From a UI perspective it is nice if the list like LVGLDir, SYMBOL and KEYS can collapse. 
With increasing features some of the lists become long to scroll.

Strictly speaking the KEYS in LVGL are en enumeration to but in the UI there is no need difference between constants and enumerations.

**Comment by mvladic** [comment]
I will add $LVGLKey enumeration for now. And later we can improve Expression Builder UI so LVGL.LV_SYMBOL_... are collapsible.

**Comment by mvladic** [comment]
Implemented.

![image](https://github.com/user-attachments/assets/5104a1a0-52f9-49a7-a7f4-401e88dcc9e6)

**Comment by fietser28** [comment]
Working fine. Thank you!
