### ISSUE TITLE
[Dashboard] Unable to switch instuments in run mode

### ISSUE THREAD

**Issue by dong-king** [eez-open/studio#471]
**Describe the bug**
Unable to switch instuments in run mode.

**To Reproduce**
1. in run mode, click `instr2` in the upper right corner
![image](https://github.com/user-attachments/assets/2fc4a9f5-6f4e-42f7-8877-c8d81e531a29)

2. select another instrument: inst1
![image](https://github.com/user-attachments/assets/55e62876-58c6-4c61-85cb-3ef3f5697f6e)

3. What is displayed in the upper right corner is still the inst2 instrument

in debug mode, it works well.

**Desktop (please complete the following information):**
 - OS: win10
 - Version: eez-studio v0.14.2

**Comment by mvladic** [comment]
Fixed.
