### ISSUE TITLE
[LVGL] No settings for spinbox

### ISSUE THREAD

**Issue by elmonic** [eez-open/studio#475]
hi
Spinbox is one of the most used widgets in graphic systems. It will be great if you add settings.
As shown below:
![spinbox2](https://github.com/user-attachments/assets/2511c8fb-5c41-4c55-bc56-358284bdddc4)
Same as the settings below
![spinbox](https://github.com/user-attachments/assets/ccd31f15-85d3-4e0c-a017-d378dbeef7b5)

**Comment by mvladic** [comment]
Do you know how "Increment" is used?

**Comment by mvladic** [comment]
Implemented.

![image](https://github.com/user-attachments/assets/915b1a07-8704-4142-b1f7-337a606ea9eb)

Here is some sample project:

[spinbox_test.zip](https://github.com/user-attachments/files/16509106/spinbox_test.zip)

![image](https://github.com/user-attachments/assets/754d5658-3894-4dfc-b828-08acdfe5415b)

**Comment by elmonic** [comment]
> Implemented.
> 
> ![image](https://private-user-images.githubusercontent.com/449788/355417445-915b1a07-8704-4142-b1f7-337a606ea9eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMDg0ODksIm5iZiI6MTcyMzAwODE4OSwicGF0aCI6Ii80NDk3ODgvMzU1NDE3NDQ1LTkxNWIxYTA3LTg3MDQtNDE0Mi1iMWY3LTMzN2E2MDZlYTllYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QwNTIzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODY3YjM0M2E5NTc3YzRhYWI3NGUzNGY4YTcwMjE5MGM0MjYzNzc2NjJiOTE5MDI5NWY4YWM5Mzk3ODBmN2FhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.25jgJEun2XCdP177Ub2W9LpH6aroo9hEAQsX9XEs4O0)

Hi, thanks
Yes, it can be done with flow mode.
Will this section be added in the next version?

**Comment by mvladic** [comment]
This will be released very soon in version 0.15.1

**Comment by elmonic** [comment]
thanks
