### ISSUE TITLE
[LVGL] LV_SYMBOL_FILE symbol hex number Wrong

### ISSUE THREAD

**Issue by elmonic** [eez-open/studio#477]
The number set in the eezstudio for LV_SYMBOL_FILE is wrong, it should be changed from 0xf158 to 0xf15B.
In the image below, see the correct number of your lvgl fonts.

![font](https://github.com/user-attachments/assets/a0abc816-4f9a-477f-895e-f935167769ef)

In lv _symbol _def .h in lvgl library files it is written wrong.

![font2](https://github.com/user-attachments/assets/65b68ba7-e461-4db0-982b-c6ed65f71598)

**Comment by mvladic** [comment]
Fixed.

Thank you!

**Comment by elmonic** [comment]
your welcome
