### ISSUE TITLE
[LVGL] Generated image c file must use project defined Build - Include parameter

### ISSUE THREAD

**Issue by drik** [eez-open/studio#479]
**Describe the bug**
When I define LVGL Include parameter in my project, EEZ still generate c file with lvgl/lvgl.h 

**To Reproduce**
1. Go to Project Settings --> Build --> LVGL Include (change tthe default 'lvgl/lvgl.h' by 'lvgl.h'
2. Add an image (named xxx) to your project and Build
3. Open the generated ui_image_xxx with a text editor
4. On line 7, you can see #include "lvgl/lvgl.h"

**Expected behavior**
The build system must use LVGL Include parameter to generate ui_images

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11

**LVGL version (if used)**

- 9.x

**Comment by mvladic** [comment]
We are using [LVGL tool](https://github.com/lvgl/lv_img_conv) to generate these image files and doesn't change them afterwards. If you look closely you can see that following is generated:

```
#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif
```

So, you can add preprocessor definition `LV_LVGL_H_INCLUDE_SIMPLE` and `lvgl.h` will be included.

**Comment by petrubuciu** [comment]
i had to ask because i have the same problem, where to make this definition of LV_LVGL_H_INCLUDE_SIMPLE?
For now i'm editing every image_xx.c file to include the "lvgl.h" and not "lvgl/lvgl.h"
Sorry if my question is noob. thx in advance.

**Comment by mvladic** [comment]
> where to make this definition of LV_LVGL_H_INCLUDE_SIMPLE

Are you on Arduino?

**Comment by petrubuciu** [comment]
ESP32 s3

**Comment by mvladic** [comment]
I think you can't add preprocessor definitions using Arduino IDE.

So, I decided to prepend each generated `img_....c` file with the following:

```
#ifdef __has_include
    #if __has_include("lvgl.h")
        #ifndef LV_LVGL_H_INCLUDE_SIMPLE
            #define LV_LVGL_H_INCLUDE_SIMPLE
        #endif
    #endif
#endif
```

This should fix the issue for Arduino.

**Comment by mvladic** [comment]
Implemented as described in my previous comment.
