### ISSUE TITLE
Add license info in .deb package

### ISSUE THREAD

**Issue by prasimix** [eez-open/studio#48]

**Comment by prasimix** [comment]
Replace Proprietary license with relevant info, currently we have the following:

![screenshot from 2018-12-30 11-30-16](https://user-images.githubusercontent.com/15106476/50546443-dd71ee80-0c27-11e9-984a-13708f73c928.png)

**Comment by mvladic** [comment]
Can't fix this since it is issue with electron-builder which we use to build DEB package. See: https://github.com/electron-userland/electron-builder/issues/4270
