### ISSUE TITLE
[EEZ-STUDIO] Active line in code editor highlights the whole line masking out selected text

### ISSUE THREAD

**Issue by zalexzperez** [eez-open/studio#485]
The active line highlighting feature prevents visibility of selected text by continuing to highlight the entire line.

**Screenshots**

![image](https://github.com/user-attachments/assets/46f9027c-52c2-481c-8383-d1aae24e4907)
Believe it or not, the word "variables" is selected

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by mvladic** [comment]
Fixed.
