### ISSUE TITLE
Mixed type in query response

### ISSUE THREAD

**Issue by prasimix** [eez-open/studio#49]
Add support for mixed type in instrument query response to cover cases such as Rigol's `:DISPlay:GRADing:TIME?` query that can return MIN|0.1|0.2|0.5|1|5|10|INFinite

**Comment by Rerouter** [comment]
Based on the latest project editor, I imagine this is resolved by the type "Discrete", Or did you have something else in mind.

**Comment by prasimix** [comment]
No, this issue is added as reminder that we have to support mixed values such as _Discrete_ (MIN and INFinite), _NR1_ (5, 10) and _NR3_ (0.1, 0.2, 0.5) from the reported example.

**Comment by prasimix** [comment]
Fixed
