### ISSUE TITLE
[EEZ-STUDIO] Improve visibility of glyphs in font inspector when dark theme is applied

### ISSUE THREAD

**Issue by zalexzperez** [eez-open/studio#493]
Dark theme:
![2024-08-25 12_46_36-_ InfotronicsGUI - EEZ Studio](https://github.com/user-attachments/assets/39f3791a-dd5f-47af-a353-80e91dce5a44)

Light theme:
![2024-08-25 12_46_13-_ InfotronicsGUI - EEZ Studio](https://github.com/user-attachments/assets/272eb279-15ac-44a9-864e-34bdda4215c7)

Also, If possible, make rectangles around each glyph a little less visible, they currently stand out way too much.

**Comment by mvladic** [comment]
Fixed.
