### ISSUE TITLE
[LVGL] Support 'OR'ed properties

### ISSUE THREAD

**Issue by arturo182** [eez-open/studio#494]
Some properties in LVGL are actually a bit mask and allow for a little flexibility in how they are set.
 
One such property is [Border Side](https://github.com/lvgl/lvgl/blob/8b659fc9a2b55460950fe5b6e9534a2ff593f193/src/misc/lv_style.h#L95), you can have a border on the Left, or on the Top, but also on the Left AND the Top. Another such property is [Text Decoration](https://github.com/lvgl/lvgl/blob/8b659fc9a2b55460950fe5b6e9534a2ff593f193/src/misc/lv_style.h#L85), there might be more.

At the moment EEZ Studio has a fixed list of possible values for those properties and doesn't allow for full flexibility:
![image](https://github.com/user-attachments/assets/b0bcf7e3-bda9-4b55-ba2e-c1388b0cef85)

As for how this could be solved, for example in Qt, they have a collapsible list of checkboxes that create the ORed mask:

![image](https://github.com/user-attachments/assets/02fc0fb2-ce0f-47db-b893-5c683febfc3a)

It would be great if this found its way to EEZ Studio at some point 🙂 

Thanks!

**Comment by mvladic** [comment]
Implemented for the "Border side" and "Text decoration":

![image](https://github.com/user-attachments/assets/b8042ee8-56fd-44af-9e3b-80ccc4d32b00)

**Comment by arturo182** [comment]
Thank you :)
