### ISSUE TITLE
Dim or hide lines to hidden widgets 

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#495]
**Is your feature request related to a problem? Please describe.**
In screens/dashboards where widgets are overlays I often hide the widgets (hidden in the widget structure panel, not the hide property of the widget itself) to unclutter the screen during development.
The lines to these hidden widget are still visible.
This issue is for convenience / nice UI only.

**Describe the solution you'd like**
Dim or hide the lines to widgets hidden in the widget structure. 
It would be nice if the user can choose between dim and hide for the lines.

**Describe alternatives you've considered**
Live with the clutter.

**Additional context**
Widget hidden, lines are floating. Dimming or hiding the these floating lines is the scope of this issue.
![image](https://github.com/user-attachments/assets/7c1447cd-aafd-4017-86ed-27e36617cd8e)
Widget shown. The lines are now connected to the shown widget handles:
![image](https://github.com/user-attachments/assets/2f04a2bc-5792-4f89-9d03-34c00677222e)

**Comment by mvladic** [comment]
Implemented.

Dim or hide option can be selected here:

![image](https://github.com/user-attachments/assets/f016c595-1637-40bd-b0cf-7e7d60c98940)

or in Project Settings, where you can also change the opacity of the dimmed lines:

![image](https://github.com/user-attachments/assets/ee8c056b-5079-4766-be2c-7ffca7ecec11)

**Comment by fietser28** [comment]
It is working fine. Thank you!

I do have a text suggestion: 
Add the text "Hidden widgets lines" left of  the rolldown in the widget structure (and the rolldown can be smaller):
![image](https://github.com/user-attachments/assets/0df9c2df-5b52-46d5-abfa-45b4a953466f)
If the text doesn't fit because the panel is to small the text can be clipped.

**Comment by mvladic** [comment]
Changed as suggested.

**Comment by fietser28** [comment]
Thank you.
