### ISSUE TITLE
[LVGL] Direction option for Dropdown widget

### ISSUE THREAD

**Issue by vldgeorgiev** [eez-open/studio#501]
**Is your feature request related to a problem? Please describe.**
The Dropdown widget (lv_dropdown) supports a Direction property for placement of the list (up, down, left, right). The option is not supported by EEZ Studio.

**Describe the solution you'd like**
It will be useful if EEZ Studio ccan control that property

![image](https://github.com/user-attachments/assets/a519811b-bd21-4e2c-bf3c-fdbbcd90a08c)

**Comment by mvladic** [comment]
Implemented.

**Comment by vldgeorgiev** [comment]
@mvladic Thanks for the quick implementation. I tried it and it does work, the list  appears on the side, but there is a glitch.
The list in my case is larger (higher) than the screen and the top part gets cropped. I can scroll it, but can't select or see the top 1-2 items in it. Is that an LVGL issue or something adjustable from EEZ Studio?
<img width="337" alt="image" src="https://github.com/user-attachments/assets/64955c39-8f24-45a9-a991-8d2ee7f42d8d">

**Comment by zalexzperez** [comment]
There's another  little problem.
Both the BOTTOM and TOP directions share the same indicating arrow pointing downwards.
