### ISSUE TITLE
[LVGL] Support `lv_obj_set_scroll_snap_x` and `lv_obj_set_scroll_snap_y` 

### ISSUE THREAD

**Issue by technophil98** [eez-open/studio#505]
While scrollbar mode and scroll directions are implemented, scroll snap is not configurable from EEZ Studio.

Like scroll direction, two dropdowns could be added to select between `lv_scroll_snap_t` variants for each axis:
![image](https://github.com/user-attachments/assets/0f6d45b4-e485-4bd6-93ac-3b34e9520bf0)

A workaround is to manually call `lv_obj_set_scroll_snap_x(obj, LV_SCROLL_SNAP_CENTER)` for my container.

Implementing such a feature would allow EEZ Studio to generate code similar to the [snapping example](https://docs.lvgl.io/master/examples.html#snapping) in the LVGL doc.

Thank you for your consideration :)

**Comment by mvladic** [comment]
Implemented
