### ISSUE TITLE
[LVGL] Line widget - Invert Y generates incorrect code

### ISSUE THREAD

**Issue by bentron2000** [eez-open/studio#506]
**Describe the bug**
When inverting a line within a chart in LVGL, the correct code is generated but the line is not terminated with a semicolon.

**To Reproduce**
1. Create a chart in a LVGL Project
2. Add a line within this chart
3. Click 'Invert Y'
4. Build
5. Observe code generated in screens.c is `lv_line_set_y_invert(obj, true)` (without the terminating semicolon)

**Expected behavior**
Should generate:
`lv_line_set_y_invert(obj, true);`

**LVGL version (if used)**
9.x

**Comment by mvladic** [comment]
Fixed.
