### ISSUE TITLE
[LVGL] Rounded-corner displays support

### ISSUE THREAD

**Issue by zalexzperez** [eez-open/studio#508]
[Circular displays](https://github.com/eez-open/studio/issues/363) are supported, but there are also rectangular displays with rounded corners. Please support these too by letting the user define the corner radius in pixels.

**Comment by mvladic** [comment]
Implemented.

![image](https://github.com/user-attachments/assets/aa8c85b0-9668-4185-bfcd-494cfb9c4fcf)
