### ISSUE TITLE
[LVGL] Event handler should receive event object for both "Flow" and "Action" handler types

### ISSUE THREAD

**Issue by mvladic** [eez-open/studio#510]
Send an event object through event handler connection line:

![image](https://github.com/user-attachments/assets/b0101135-3704-4004-96bd-8a007720401e)

You can use following functions to get additional info about event:

```
Event.getCode(<event>)
Event.getCurrentTarget(<event>)
Event.getTarget(<event>)
Event.getUserData(<event>)
Event.getKey(<event>)
Event.getGestureDir(<event>)
Event.getRotaryDiff(<event>)
```

Also, you can use "Action" for "Handler type" and still get event object:

![image](https://github.com/user-attachments/assets/18ff4962-b0e3-421e-b57d-ffe34d0c3934)

But, this action must have an Input of type `event` which will receive this event object:

![image](https://github.com/user-attachments/assets/d5a45032-9982-48df-b06c-07892b58526a)

-------------

**Backward compatibly notice:**

Before, events like KEY, GESTURE, ROTARY and VALUE_CHANGED (in case of ButtonMatrix widget) were sending some specific data through event handler connection line (for example GESTURE even was sending gesture direction). Now, this is changed so that these events also sends event object, so for example you need to use `Event.getGestureDir(event)` to get the direction for GESTURE event.

**Comment by zbouslikhin** [comment]
All event functions return an event or a widget. Perhaps a bug?

This means it is only possible to get the value of a component through assigning a variable to a specific component value - unfortunately cancels out the benefit of using flow 

<img width="1274" height="707" alt="Image" src="https://github.com/user-attachments/assets/d94fe67b-497c-4517-8b78-b88a9da67698" />
