### ISSUE TITLE
0.16.0 version the settings page can not see theme set, There is a problem with the interface layout in settings

### ISSUE THREAD

**Issue by LonlyPan** [eez-open/studio#514]
**Describe the bug**
I just tray the new version 0.16.0， the settings page can not see theme set, There is a problem with the interface layout in settings
it is ok on 0.15.1 version。
**Screenshots**
As shown below, I can’t see the theme settings button. I tried to stretch the interface and I can see it a little bit, but this is definitely not normal.
![图像 1](https://github.com/user-attachments/assets/65e4fb3d-b028-4337-90a6-e83f485ddbb7)
![图像 2](https://github.com/user-attachments/assets/06fcdd32-4dcc-481e-8661-b1e4c5b411da)

**Comment by mvladic** [comment]
Fixed.
