### ISSUE TITLE
Undesired widget name change after renaming image with similar name

### ISSUE THREAD

**Issue by zalexzperez** [eez-open/studio#526]
Original image name was `icon_cruise_control_gray`.
Its associated image widget was named `cruiseControl`.

I renamed image from the bitmaps panel to have prefix "img_" so it became `img_cruise_control_gray`.
However,  after renaming the image, Studio also changed the name of its associated widget to `img_cruiseControl`

**Comment by mvladic** [comment]
I haven’t been able to reproduce the problem.

**Comment by mvladic** [comment]
![#526](https://github.com/user-attachments/assets/23400f67-f383-492c-b8d9-3baf3673e35f)

**Comment by zalexzperez** [comment]
Me neither.
