### ISSUE TITLE
Size too small for 4k monitor

### ISSUE THREAD

**Issue by hiperiondev** [eez-open/studio#542]
When I use it on a 4k monitor (resolution: 3840x2160)  everything looks too small. It should be possible to change it.

**Comment by mvladic** [comment]
There is "Zoom In" under "View" menu, you can try with that.

What OS are you using?

**Comment by hiperiondev** [comment]
Perfect!!! I hadn't seen it!
Thank you so much for the reply.

Fedora 40 BTW
