### ISSUE TITLE
[LVGL] Application crashing when editing LVGL Dropdown Menu widget with screen applied style.

### ISSUE THREAD

**Issue by lylezumbrun** [eez-open/studio#544]
Application crashes when editing a dropdown menu widget size has been added to a page with applied style.

**To Reproduce**
1. Add page and apply a screen style with the background and text color set
2. Add a drop down menu and adjust the size of the drop down menu

**Screenshots**

**Desktop (please complete the following information):**
  Operating System: Linux Mint 20.1
  Kernel: Linux 5.4.0-167-generic
 Architecture: x86-64

** LVGL version (if used)**

- 8.x

**Comment by lylezumbrun** [comment]
I have attached a video showing the error.

https://github.com/user-attachments/assets/a4e07e0e-2ebb-4057-b3ba-7e4999037fc3

**Comment by mvladic** [comment]
We are doing almost the same thing, so something else in your project is causing the crash. Can I see all style modifications in your "Dark Screen" style? Or, if you can send me your project so I can investigate more directly.

**Comment by lylezumbrun** [comment]
I have uploaded my project here:
[EEZ-Display-master.zip](https://github.com/user-attachments/files/17060705/EEZ-Display-master.zip)

**Comment by mvladic** [comment]
Thanks! Now I was able to reproduce the problem.

**Comment by lylezumbrun** [comment]
Thanks for you hard work! This software is really helpful!!!

**Comment by mvladic** [comment]
This is fixed now in the master branch. FYI Next version 0.17.0 will be released by Oct 1.
