### ISSUE TITLE
[LVGL] Add LV_INDEV_TYPE_KEYPAD and LV_INDEV_TYPE_ENCODER in simulator

### ISSUE THREAD

**Issue by bentron2000** [eez-open/studio#545]
It would be very useful to be able to use the computer keyboard and mouse scroll wheel as input devices when building in studio, so that interfaces can be interacted with during simulation before deployment to a device.

Keyboard would simulate LV_INDEV_TYPE_KEYPAD, and
Scrollwheel would simulate LV_INDEV_TYPE_ENCODER

I imagine that to make the encoder simulation properly useful within the simulator would require the 'group' functionality to be available also. #229 

Original discussion on discord:
https://discordapp.com/channels/511131497801973761/853620020411629598/1286300188738064456

**Comment by mvladic** [comment]
This feature is now implemented.

This feature is also related to the feature #229. You can now define groups of widgets and you can select one group to be used for the encoder in the simulator and one group to be used for the keyboard in the simulator:

![image](https://github.com/user-attachments/assets/d394bab2-d4a4-4447-a037-7ce34ac32171)
