### ISSUE TITLE
[LVGL] Code generation error in screens.c when assigning variable to Roller.

### ISSUE THREAD

**Issue by tobinieil04** [eez-open/studio#551]
**Describe the bug**
A code generation bug occurs in EEZ Studio when using LVGL v9.x. The bug appears when trying to assign a variable to the **options** property of an **lvgl_roller** object. The issue manifests in the generated **screens.c** file within the **src/ui** directory after building the project. Despite updating EEZ Studio to version 16.1, the bug persists.*

**To Reproduce**
1. Create new LVGL project in EEZ Studio 16.1 (latest).
2. Add Roller object to main page.
3. Create a global string variable and assign to roller **options** in properties.
4. Hit build.
5. Check generated screens.c file in output **src/ui** directory.

**Expected behavior**
The generated screens.c file should correctly reflect the assignment of the variable to the options property of the lvgl_roller object, with no errors.

Actual Behavior:

- The variable assignment to the options property of the lvgl_roller object is incorrectly handled in the generated screens.c file, resulting in incorrect code generation.

- This issue appears exclusively in the screens.c file after building the project.

**Screenshots**
With variable on roller object:
![image](https://github.com/user-attachments/assets/bb9f44df-100a-4d80-b34e-6b44fbe61f14)

Without variable on roller object:
![image](https://github.com/user-attachments/assets/d3281aa1-37a8-4a79-a995-3445f453dce0)

**Desktop**
 - OS: Ubuntu Desktop
 - Version 24.04 LTS

** LVGL version (if used)**
- 9.x

**Additional context**
I am available to provide additional details

**Comment by mvladic** [comment]
Fixed.
