### ISSUE TITLE
After Update Macos M1 Sequoia 15.0 - EEZ Studio 16.1 App Crash!

### ISSUE THREAD

**Issue by LEKPCSTEAM** [eez-open/studio#556]
**Screenshots**
<img width="624" alt="Screenshot 2567-09-28 at 13 28 41" src="https://github.com/user-attachments/assets/ea06b1f5-ccd3-4ad6-8c6f-7dac675101b3">

<img width="1440" alt="Screenshot 2567-09-28 at 13 23 54" src="https://github.com/user-attachments/assets/6c4e958c-5992-45e7-ae89-5f4808cc7851">

**Desktop (please complete the following information):**

 - OS: MacOS M1
 - Version : Sequoia 15.0

** LVGL version (if used)**

- 8.x or 9.x

**Report**

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               EEZ Studio [46858]
Path:                  /private/var/folders/*/EEZ Studio.app/Contents/MacOS/EEZ Studio
Identifier:            hr.envox.eez.studio
Version:               0.16.1 (0.16.1)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-09-28 13:27:30.0173 +0700
OS Version:            macOS 15.0 (24A335)
Report Version:        12
Anonymous UUID:        59834C9C-83C2-881F-4893-B8F6AD52F92E

Sleep/Wake UUID:       BFC7A2B7-DCAF-485F-940F-5D05919A73D1

Time Awake Since Boot: 37000 seconds
Time Since Wake:       3477 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x000000010b7e1d38

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [46858]

Thread 0 Crashed:: CrBrowserMain Dispatch queue: com.apple.main-thread
0   Electron Framework            	       0x10b7e1d38 electron::fuses::IsLoadBrowserProcessSpecificV8SnapshotEnabled() + 45844
1   Electron Framework            	       0x10b7e1d38 electron::fuses::IsLoadBrowserProcessSpecificV8SnapshotEnabled() + 45844
2   Electron Framework            	       0x10b7f76d4 v8::internal::GetCurrentStackPosition() + 35436
3   libswiftCore.dylib            	       0x1927c7a10 _swift_release_dealloc + 56
4   libswiftCore.dylib            	       0x1927c8a64 bool swift::RefCounts<swift::RefCountBitsT<(swift::RefCountInlinedness)1>>::doDecrementSlow<(swift::PerformDeinit)1>(swift::RefCountBitsT<(swift::RefCountInlinedness)1>, unsigned int) + 160
5   libobjc.A.dylib               	       0x18141bd94 AutoreleasePoolPage::releaseUntil(objc_object**) + 204
6   libobjc.A.dylib               	       0x181418138 objc_autoreleasePoolPop + 260
7   CoreFoundation                	       0x18188c7c0 _CFAutoreleasePoolPop + 32
8   AppKit                        	       0x1854033c0 -[NSApplication finishLaunching] + 1772
9   AppKit                        	       0x185402a98 -[NSApplication run] + 252
10  Electron Framework            	       0x10e94b318 node::GetArrayBufferAllocator(node::IsolateData*) + 17973960
11  Electron Framework            	       0x10e949184 node::GetArrayBufferAllocator(node::IsolateData*) + 17965364
12  Electron Framework            	       0x10e901ed4 node::GetArrayBufferAllocator(node::IsolateData*) + 17673860
13  Electron Framework            	       0x10e8c8abc node::GetArrayBufferAllocator(node::IsolateData*) + 17439340
14  Electron Framework            	       0x10da5b164 node::GetArrayBufferAllocator(node::IsolateData*) + 2310420
15  Electron Framework            	       0x10da5cbfc node::GetArrayBufferAllocator(node::IsolateData*) + 2317228
16  Electron Framework            	       0x10da58ad4 node::GetArrayBufferAllocator(node::IsolateData*) + 2300548
17  Electron Framework            	       0x10b8f5288 v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 13948
18  Electron Framework            	       0x10b8f63f0 v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 18404
19  Electron Framework            	       0x10b8f6220 v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 17940
20  Electron Framework            	       0x10b8f4acc v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 11968
21  Electron Framework            	       0x10b8f4c6c v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 12384
22  Electron Framework            	       0x10b5c62f0 ElectronMain + 128
23  dyld                          	       0x181464274 start + 2840

Thread 1:
0   libsystem_pthread.dylib       	       0x1817e20e8 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x1817e20e8 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x1817e20e8 start_wqthread + 0

Thread 4:: ThreadPoolServiceThread
0   libsystem_kernel.dylib        	       0x1817b1bdc kevent64 + 8
1   Electron Framework            	       0x10e954e20 node::GetArrayBufferAllocator(node::IsolateData*) + 18013648
2   Electron Framework            	       0x10e954654 node::GetArrayBufferAllocator(node::IsolateData*) + 18011652
3   Electron Framework            	       0x10e901ed4 node::GetArrayBufferAllocator(node::IsolateData*) + 17673860
4   Electron Framework            	       0x10e8c8abc node::GetArrayBufferAllocator(node::IsolateData*) + 17439340
5   Electron Framework            	       0x10e9230e0 node::GetArrayBufferAllocator(node::IsolateData*) + 17809552
6   Electron Framework            	       0x10e90ba78 node::GetArrayBufferAllocator(node::IsolateData*) + 17713704
7   Electron Framework            	       0x10e923220 node::GetArrayBufferAllocator(node::IsolateData*) + 17809872
8   Electron Framework            	       0x10e936934 node::GetArrayBufferAllocator(node::IsolateData*) + 17889508
9   libsystem_pthread.dylib       	       0x1817e72e4 _pthread_start + 136
10  libsystem_pthread.dylib       	       0x1817e20fc thread_start + 8

Thread 5:: ThreadPoolForegroundWorker
0   libsystem_kernel.dylib        	       0x1817a5e34 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1817b85d0 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1817ae9d8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x1817a617c mach_msg + 24
4   Electron Framework            	       0x10e94e0e0 node::GetArrayBufferAllocator(node::IsolateData*) + 17985680
5   Electron Framework            	       0x10e8e0bdc node::GetArrayBufferAllocator(node::IsolateData*) + 17537932
6   Electron Framework            	       0x10e91c6e8 node::GetArrayBufferAllocator(node::IsolateData*) + 17782424
7   Electron Framework            	       0x10e91c054 node::GetArrayBufferAllocator(node::IsolateData*) + 17780740
8   Electron Framework            	       0x10e91bf2c node::GetArrayBufferAllocator(node::IsolateData*) + 17780444
9   Electron Framework            	       0x10e936934 node::GetArrayBufferAllocator(node::IsolateData*) + 17889508
10  libsystem_pthread.dylib       	       0x1817e72e4 _pthread_start + 136
11  libsystem_pthread.dylib       	       0x1817e20fc thread_start + 8

**Comment by mvladic** [comment]
This is already reported in #537 and fixed in the master branch. The new Studio will be released in couple of days.

**Comment by LEKPCSTEAM** [comment]
> This is already reported in #537 and fixed in the master branch. The new Studio will be released in couple of days.

Thank you for your support. 🫡🥰
