### ISSUE TITLE
Non-intrusive persistent indicator of project built state

### ISSUE THREAD

**Issue by zalexzperez** [eez-open/studio#558]
Large projects take some time to build. 
I've ran into the next annoying situation multiple times since one of my projects has become large enough: you press the build button, quickly leave the program and return some time later. But then you become unsure whether you actually built the project or not. 

Currently, the only indicator is this toast message that gets closed automatically after some timeout value:

![image](https://github.com/user-attachments/assets/8d92c6bc-64f8-4fea-bf74-1ca29288c4b6)

This toast message is too intrusive not to auto close it.

So I propose a permanent non-intrusive indicator that remains active as long as the project state wasn't changed since the moment the project was built. Changes in the code editor should be detected as well.

My idea is to make the Output indicator tick green:

![image](https://github.com/user-attachments/assets/279159cf-5ec3-40b6-9ff8-44eabc72d2b2)

As an extra, if we make some changes and then undo them, the indicator can recover the green status.

**Comment by mvladic** [comment]
Implemented.
