### ISSUE TITLE
[LVGL] Add group action to save the current focused object 

### ISSUE THREAD

**Issue by zalexzperez** [eez-open/studio#559]
Currently, when a screen is loaded, the first object in the group gets focused by default.

By allowing the user to save the current focused object in a variable with an LVGL group action, we will be able to later restore the focus on this object when required (e.g. when returning from another screen).

This feature request requires being able to read from variables when using the LVGL action to focus on an object, which is also not currently possible.

**Comment by mvladic** [comment]
This issue will be solved by implementing issue #570.
