### ISSUE TITLE
Encoder group navigation using scroll wheel conflicts with scrolling inside of Studio in debug mode

### ISSUE THREAD

**Issue by zalexzperez** [eez-open/studio#561]
https://github.com/user-attachments/assets/188d3779-73b5-48e2-8212-1bfb6bdd20ef

Perhaps encoder navigation should use ALT + mouse wheel just like it's done in Edit mode to navigate UIs that are larger than the display size.

**Comment by mvladic** [comment]
Fixed.

If mouse pointer is inside LVGL screen canvas then mouse wheel will affect LVGL, otherwise it will affect page viewer.
