### ISSUE TITLE
Error generating bitmap

### ISSUE THREAD

**Issue by Obili69** [eez-open/studio#562]
**Describe the bug**
I have pypng installed but stiell get the error 
werror generating bitmap 'ui_image_logo_logo2.c' file: Error: ImportError: Need pypng paCKAGE, DO `pip3 install pypng`
(I have pypng installed)
**To Reproduce**
Import a png and add it on a screen. This leads to the above discribed logo.

**Expected behavior**
For it to compile

**Screenshots**
<img width="2560" alt="image" src="https://github.com/user-attachments/assets/6d66b95e-bc54-401c-ab50-579c7ddc57b9">

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Version [15.1]

** LVGL version (if used)**

9.x

**Additional context**
![logo](https://github.com/user-attachments/assets/f7dedc1a-a270-4a4d-ae43-bfb8235cd60f)

**Comment by mvladic** [comment]
Because you are on the Mac, usually this means that Studio is using different python then the python you see from the command line. [Check this issue](https://github.com/eez-open/studio/issues/346), in the comments you will find how to set custom python path in Studio.
