### ISSUE TITLE
Collapse comment widgets to hide/show text inside

### ISSUE THREAD

**Issue by zalexzperez** [eez-open/studio#567]
Clicking on the top part of the widget could collapse the text area for organization and aesthetic purposes.
Another improvement could be to move Description field from the bottom to the top, so we can add a Comment title to know what the note is about, like this:

![image](https://github.com/user-attachments/assets/6d183cf6-af61-4f79-b2fe-6b295aec8bd8)

**Comment by mvladic** [comment]
Implemented.

Use double click to open/close comment.
