### ISSUE TITLE
[LVGL] Object search in LVGL actions doesn't work

### ISSUE THREAD

**Issue by zalexzperez** [eez-open/studio#572]
Example:
![image](https://github.com/user-attachments/assets/218c0b2b-5248-468a-9b7f-e4a9a17cb444)

Also, as it can be seen in the screenshot, there's a spelling checker functionality enabled by default that can be confusing. 
Please, implement a way to disable it.

**Comment by mvladic** [comment]
Fixed.

**Comment by mvladic** [comment]
I agree this could be confusing. I made a change so that the search text is cleared every time this dialog is opened.
