### ISSUE TITLE
EEZ crashes (MacOS) within 10-15 seconds of loading Roboto Regular.ttf font in size 172 for numbers

### ISSUE THREAD

**Issue by yaredna** [eez-open/studio#580]
**Describe the bug**
Created a LVGL project, one screen, one label with the text "00.0". Loaded a google font Roboto Regular.ttf, only numbers (32, 42-58) in size 172. The EEZ editor crashes with a blank unresponsive screen within 10-15 seconds from creating the font. 

**To Reproduce**
Create new LVGL 8.3 project. Create a Roboto_172 font using Google's Roboto Regular, size 172, range (32, 42-58). Change the text of the Hello, world! label to "00.0", and font to Roboto_172. Keep working. The editor will crash 100% of the time within 15 seconds with a white screen, unresponsive. 

**Expected behavior**
Expec the program to continue working as the font loaded properly. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version : Sonomo 14.6.1

** LVGL version (if used)** 

- 8.3

------
Update : great news, it works on an another Mac (my wife's Mac). So now I need to investigate what is wrong with the specific configuration on my laptop. Maybe a fresh re-installation will take of it. Will close the issue shortly

**Comment by mvladic** [comment]
It doesn't seem to crash on Windows, I'll test on Mac tomorrow.

![image](https://github.com/user-attachments/assets/59304a5c-bdc7-417a-8b79-67c43d7738db)

**Comment by yaredna** [comment]
Let try the same example on a different version but I will also try it on my wife’s laptop too. Thanks so much !! Will send the files if I can repeat the crash on my wife’s Mac !!Sent from my iPhoneOn Oct 11, 2024, at 4:20 AM, Martin Vladić ***@***.***> wrote:﻿
It doesn't crash on my Mac too (however, I have macOS 15).

Happy to send you the files if you need.

Yes, please, send me your eez-project file.

**Comment by yaredna** [comment]
Excellent. After receiving your message, I went ahead and test it on my wife’s Intel Mac, and it worked. I will try figuring out why it crashes on my system: must be related to my installation. 

Let me know please;
1. Do you want me to delete the post or should I update it there is no issue 
2. The project that crashed my system is attached. Let me know if you need other files. 

Thanks so much !!!!!!
Nadim
￼

**Comment by mvladic** [comment]
I don't see attached project. You should zip your eez-project file before attaching here on github.

**Comment by yaredna** [comment]
Sorry ! Here is the zip file attached. Do you also need the files generated by the export too ? 
￼

**Comment by yaredna** [comment]
[WindAlarm.eez-project-ui-state.zip](https://github.com/user-attachments/files/17348414/WindAlarm.eez-project-ui-state.zip)

The email interface to this forum doesn't permit attachments. Sorry. I am attaching the file hereby. I will edit the original post to reflect that it worked fine on another Mac, and could be configuration specific.

**Comment by yaredna** [comment]
I believe now that the issue is specific to my personal Mac, probably a configuration issue. It is working fine on my wife's Mac. I included the zip file here just in case, but I am closing this issue. Great response from the team, super impressed !! Moving my entire project from Squareline to EEZ is likely to happen in the new few days.
