### ISSUE TITLE
[EEZ Flow] Action widget distinction for native user actions

### ISSUE THREAD

**Issue by zalexzperez** [eez-open/studio#582]
Flow and Native user actions share the same looks.

To have more information, I propose a distinguished look for native actions, for example:

![image](https://github.com/user-attachments/assets/d9dc5ac2-760f-4d71-bf20-a9fbeb49630d)

**Comment by mvladic** [comment]
Implemented.

**Comment by zalexzperez** [comment]
I appreciate the change. I don't want to be annoying, but please, consider this.

Right now, the User Actions section looks like this:

![image](https://github.com/user-attachments/assets/9c8abe04-6b98-4496-92d8-a6b7cd4543b7)

But you may not remember what the lighter or darker green stands for. If you hover over the widget, you also don't get information about whether it's a native or a flow action.

This gets worse when you have the widget in the design area, without anything to compare it with:

![image](https://github.com/user-attachments/assets/8a56a3b2-cbcd-471f-9940-378c6200862e)

To be able to easily tell what type of action it is at first glance, I'd add an extra touch to help with that, without confusing anyone. Two ideas:

- Something inside the parenthesis: `(/)` or `(#)`
- Something more subtle: for example, using curly braces for native actions: 
![image](https://github.com/user-attachments/assets/48b8025e-8cb2-44ba-a978-7508dd91d11c)

I particularly prefer the last one. If you don't like any of the two, that's fine.

Also, when selecting the user action, properties panel could show it's a native action:

![image](https://github.com/user-attachments/assets/ff842cf7-316a-4df9-a99d-099ba10cb4b1)

And finally, like mentioned before, hovering mouse cursor over the action, could indicate it as well:
![image](https://github.com/user-attachments/assets/bd42fe4e-9816-4a19-ab5d-b737af817c42)

**Comment by mvladic** [comment]
> Something more subtle: for example, using curly braces for native actions

Implemented.
