### ISSUE TITLE
[LVGL] In the SPECIFIC properties of the arc widget, REVERSE and SYMMETRIC are swapped.

### ISSUE THREAD

**Issue by LonlyPan** [eez-open/studio#586]
**Describe the bug**
In the SPECIFIC properties of the arc widget, REVERSE and SYMMETRIC are swapped.

**Screenshots**
![图像-20241013-173417](https://github.com/user-attachments/assets/68d89ffb-23b9-4625-9ef1-b26da90f8eb8)
![图像-20241013-173428](https://github.com/user-attachments/assets/4dc0dd9a-a40a-4299-9b5f-83e6d9c58c02)

**Desktop (please complete the following information):**
 - Windows
 - Version  0.18.2 and 0.18.0

** LVGL version (if used)**
-  9.x

**Comment by mvladic** [comment]
Fixed.
