### ISSUE TITLE
[LVGL] Backslash is not handled properly in Text property

### ISSUE THREAD

**Issue by Bagietas** [eez-open/studio#589]
**Is your feature request related to a problem? Please describe.**
Putting _backslash_ in Text Property doesn't handle it properly, and leads to generating wrong string (I don't know how to explain it)

**Describe the solution you'd like**
Handle it (add another _backslash_)

**Describe alternatives you've considered**
Now I'm adding one more _backslash_ to "fix" it.

**Additional context**
Those 2 images explain it correctly.
![image](https://github.com/user-attachments/assets/35678d76-3c88-4359-9a42-e2dda071b0d8)
![image](https://github.com/user-attachments/assets/dd461c59-8878-4fe4-a6e4-821589623fd2)

**Comment by mvladic** [comment]
Fixed.
