### ISSUE TITLE
[LVGL] Support strings for roller options (Expression type)

### ISSUE THREAD

**Issue by zalexzperez** [eez-open/studio#592]
**Is your feature request related to a problem? Please describe.**
Currently, roller options are passed using an array of strings when selecting Expression type.
However, LVGL documentation states that roller options are passed as a string.

**Describe the solution you'd like**
Accept strings and not just array of strings

**Additional context**
Using strings to set the options allows easily creating rollers with variable amounts of options.

**Comment by mvladic** [comment]
Implemented.
