### ISSUE TITLE
[EEZ Flow] Properties panel doesn't show action's properties when double clicking action widget

### ISSUE THREAD

**Issue by zalexzperez** [eez-open/studio#595]
Double clicking on an action widget loads action page but in properties panel, widget properties are still shown, where you can select different actions:

![image](https://github.com/user-attachments/assets/e956606d-8515-4125-8eef-1f0232b50a7a)

What would be expected is to view the actual action's properties, like when you select the action from the User Actions panel list:

![image](https://github.com/user-attachments/assets/1be26b4e-28a5-4916-9649-128690f0a893)

As noted in Discord, after action page is loaded, middle-mouse clicking on an empty space brings the appropriate properties into view. 

And one last comment: as it can be seen on the first screenshot, widget properties does not carry the [NATIVE] tag on the action name at the top, which for consistency's sake should be there in my opinion.

**Comment by mvladic** [comment]
Fixed.
