### ISSUE TITLE
Redundant information in instrument terminal (session) view

### ISSUE THREAD

**Issue by prasimix** [eez-open/studio#60]
Remove redundant information about closed session if no instrument activity was recorded during the session.

![screenshot from 2019-01-13 15-14-15](https://user-images.githubusercontent.com/15106476/51102106-fceb4880-17dd-11e9-98e3-3fd48811e20f.png)

**Comment by mvladic** [comment]
For this particular case, information about closed session is not redundant because there are deleted items that are created during session.
