### ISSUE TITLE
[LVGL] Wrong native action function name in `actions.h`

### ISSUE THREAD

**Issue by zalexzperez** [eez-open/studio#609]
I created a native action called `query_OBD2_task_mgr` but in actions.h I have:

`action_query_ob_d2_task_mgr(lv_event_t * e);`
I was expecting it to be `action_query_obd2_task_mgr(lv_event_t * e);`

OBD2 word in lowercase does not show this problem.

**Comment by mvladic** [comment]
Fixed.
