### ISSUE TITLE
[LVGL] add state LV_STATE_EDITED

### ISSUE THREAD

**Issue by elmonic** [eez-open/studio#610]
Hello, thank you for the new version
Thanks for adding the group and encoder to the program. Now, after adding this EDITED state condition to the software, add it to the styles section because it helps to recognize the current state of the widget.

![add edit state](https://github.com/user-attachments/assets/661d6c12-7a5e-4d52-b33b-93727cabe6c5)

**Comment by mvladic** [comment]
Implemented.
