### ISSUE TITLE
Manipulation of flow node view with touchpad

### ISSUE THREAD

**Issue by ajayre** [eez-open/studio#618]
This is what I currently am working with:

![Screenshot 2024-11-02 221952](https://github.com/user-attachments/assets/58fabb11-9372-44a6-987f-63a26b131c91)

It would be nice if there were scrollbars for the view area so I can zoom in and then pan around. Also a zoom to fit everything would be nice.

If I right-click and choose Center View then it wastes a lot of space on the left.

Perhaps this is easier with a mouse but I am using a laptop with a touchpad and it is getting a bit unwieldy and painful to use.

Thanks.

**Comment by mvladic** [comment]
> Perhaps this is easier with a mouse but I am using a laptop with a touchpad and it is getting a bit unwieldy and painful to use.

With the mouse you can use middle or right button to pan around. With the touchpad I only tested with the Mac and panning with two fingers and pinch to zoom works good in my opinion. I just tested on the Linux Acer laptop and panning with two fingers works, but as you say it is unwieldy to use, i.e. it is to sensitive. On this laptop pinch to zoom doesn't work at all.

**Comment by mvladic** [comment]
Panning and zooming on Lenovo Thinkpad laptop on Windows also works good. What operating system are you using?

**Comment by ajayre** [comment]
Windows 11.

Pinch to zoom works. Two fingers to pan doesn't work.

**Comment by mvladic** [comment]
> Two fingers to pan doesn't work.

Does it not work at all or does it sometimes mix panning and zooming (because both gestures use two fingers)?

**Comment by ajayre** [comment]
Doesn't do anything at all.

**Comment by mvladic** [comment]
Hm, it works on my Lenovo Thinkpad X1 Extreme WIndows 11 laptop. Does two finger panning/scrolling work in other programs?

**Comment by mvladic** [comment]
>Hm, it works on my Lenovo Thinkpad X1 Extreme WIndows 11 laptop

On this laptop I have an option to enable/disable two finger scrolling:

![image](https://github.com/user-attachments/assets/47822a52-0ad6-4f2e-971b-34192171e43c)

**Comment by ajayre** [comment]
Yes. I couldn't live without it. For example works in Chrome, Notepad++, Visual Studio, etc.

**Comment by ajayre** [comment]
Note that two-finger panning would be nice but I am perfectly happy with scroll bars.

**Comment by mvladic** [comment]
Ok, I will investigate how scroll bars can be added. There is a complications because page view editor can grow indefinitely in all directions.

I'm curious, what is your laptop model? Maybe I can find a similar laptop to reproduce this problem.

**Comment by mvladic** [comment]
BTW on my Thinkpad laptop, panning also works with one finger if I keep pressed right touchpad button (right button press is detected when I press touchpad on the bottom right corner of the touchpad).

**Comment by ajayre** [comment]
Yes, I understand the technical difficulty...

I just tried it, right-click and drag does work for panning.

**Comment by ajayre** [comment]
Instead of scrollbars how about toolbar buttons for zoom and pan modes?

**Comment by mvladic** [comment]
For now, I made a change so you can pan around with the ALT key + "single finger drag".
