### ISSUE TITLE
[LVGL] Include font fallback

### ISSUE THREAD

**Issue by JomaImport** [eez-open/studio#620]
In many cases it is very helpful to have a fallback for every font, I guess it will be a good idea and very easy to implement, just give the user the possibility to select the fallback font.

**Comment by mvladic** [comment]
Are we talking about Dashboard project or LVGL project?

**Comment by JomaImport** [comment]
LVGL 8.X

    .dsc = &font_dsc,          /*The custom font data. Will be accessed by `get_glyph_bitmap/dsc` */
    .fallback = NULL,
    .user_data = NULL

In the generated code in the font C file the .fallback is always NULL, it would be helpful if the user could select the fallback font at design time

**Comment by mvladic** [comment]
I didn't know about that. Do you know under what circumstances this fallback font will be used?

**Comment by JomaImport** [comment]
A fallback is used when one character is not found in the current font, in that case is used the character in the fallback font, so can be used in many cases when the needed character is not found in the generated font.

As an example you can see the two next pictures, the first one is a messagebox using the deult Montserrat font, the second picture uses a generated font and as you will see the X symbol for closing it is not in the generated font so is not displayed. If the Montserrat font is define as fallback font then this symbol is displayed correctly.

For your information we are using ESP-IDF for ESP32-S3.

![EEZ_Studio_yr99OvarA8](https://github.com/user-attachments/assets/3e51fc08-164a-42f0-acf5-b07fad4b7908)
![EEZ_Studio_Dz6iS8fAmJ](https://github.com/user-attachments/assets/89b66512-6e79-4237-9ced-dfaa3973e51f)

**Comment by JomaImport** [comment]
The same issue happens with other widgets like dropdown 

![EEZ_Studio_0Jz85nOrU2](https://github.com/user-attachments/assets/274a5ab0-dd93-46e5-a5f9-7f18896f1e21)
![EEZ_Studio_NzaeFyD8No](https://github.com/user-attachments/assets/95a54c3b-cadb-4271-b454-e998cf8f9393)

**Comment by mvladic** [comment]
All clear, thanks!

**Comment by mvladic** [comment]
Implemented.

![image](https://github.com/user-attachments/assets/0b0df4b6-bc68-4511-98cc-ef4d713639b4)

**Comment by JomaImport** [comment]
Thanks for implementing so quickly!
