### ISSUE TITLE
[LVGL] Groups index problem

### ISSUE THREAD

**Issue by elmonic** [eez-open/studio#629]
hi thank for new version
eez studio When creating a group, the first widget is wrongly placed in the last widget.
![group](https://github.com/user-attachments/assets/d9508fab-86b4-44b6-8f16-e9d6a06cf4c6)

**Comment by mvladic** [comment]
I don't know how to reproduce this problem. Can you send me the eez-project file in which this problem occurs?

**Comment by elmonic** [comment]
For example, you create a group and then create several series of widgets. Now add a group to the widgets and specify the number of each widget in the group.
After this, you will see that widget number zero is placed in the group list as the last widget. Now, when the code is created, the first widget is placed at the end.

**Comment by mvladic** [comment]
So, if you want to use "Group index" to control the order of widgets in group then use values 1, 2, 3, ... as value 0 will always put the widget at the end.

**Comment by elmonic** [comment]
OK, thank you, but if it starts from scratch, it is more basic.

**Comment by elmonic** [comment]
OK, thank you, but if it starts from zero, it is more basic.
