### ISSUE TITLE
[LVGL] White screen while coping font from one project to another

### ISSUE THREAD

**Issue by JJZBQA** [eez-open/studio#632]
<img width="1277" alt="1731484237632" src="https://github.com/user-attachments/assets/e97fed91-3627-4a86-b963-5eb60db1d4c7">
I copied the text Font from one project to another, and after running for a while, a white screen appeared. Regardless of whether I close it or open other projects, the same issue occurs — it runs for a while and then the screen turns white.

**Comment by mvladic** [comment]
If this happens again open Developer Tools:

![image](https://github.com/user-attachments/assets/2f757dab-e0d2-44d3-9800-e61010f647be)

and then save the console log with the right click context menu:

![image](https://github.com/user-attachments/assets/eda432f9-abe8-4b06-a9b9-55f9ea574ad2)

**Comment by JJZBQA** [comment]
![image](https://github.com/user-attachments/assets/0a5c9816-1c9c-4832-857b-ee1b4b0b4eb6
<img width="582" alt="1731582821590" src="https://github.com/user-attachments/assets/fac751cf-d01a-4417-8651-1277b0e6fa95">
[-1731582849906.log](https://github.com/user-attachments/files/17747736/-1731582849906.log)
[-1731582956028.log](https://github.com/user-attachments/files/17747755/-1731582956028.log)
[-1731582966382.log](https://github.com/user-attachments/files/17747758/-1731582966382.log)

Happen again

**Comment by mvladic** [comment]
What OS and Studio version you are using?

**Comment by JJZBQA** [comment]
Windows11，Latest version
---- Replied Message ----
From Martin ***@***.***> Date 11/14/2024 19:23 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [eez-open/studio] white screen (Issue #632) 
What OS and Studio version you are using?

**Comment by mvladic** [comment]
> Windows11，Latest version

You compiled the latest version from the source?

**Comment by mvladic** [comment]
> I downloaded the latest version you compiled.

Ok. I believe I fixed this problem. You can wait a several days until I release version 0.20.0 or you can build from source to test it now.

**Comment by JJZBQA** [comment]
Thank you very much.And today, when I moved a component, I pressed the shortcut key to save it, and then my project was very big, which also triggered such a bug once.The preservation time has also become very long. ***@***.*** ***@***.*** ---- Replied Message ---- From Martin ***@***.***> Date 11/14/2024 21:15 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [eez-open/studio] [LVGL] White screen while coping font from one project to another (Issue #632) I found a memory leak while coping font from one project to another. So, this could be the issue you are experiencing. It is fixed now. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>
