### ISSUE TITLE
[LVGL] Add "screen stack control" property to Change Screen action

### ISSUE THREAD

**Issue by zalexzperez** [eez-open/studio#649]
If we need to change screen without adding the active one to the stack, we need the missing Set Active Screen action. 
In order not to create a new action just for this, it makes sense to have a "Put active screen on the stack" option - enabled by default - on the Change Current screen action.

**Comment by mvladic** [comment]
Implemented.

I added a new property called "Use stack":

![image](https://github.com/user-attachments/assets/0a0cbba6-6972-4495-97b0-2046664d664c)

**Comment by zalexzperez** [comment]
The property seems to come disabled by default. And also, it's marked in red as if it requires user intereaction
![image](https://github.com/user-attachments/assets/532e6e94-64ae-439a-b9cf-bf1ca5eb1e8b)

**Comment by mvladic** [comment]
> The property seems to come disabled by default.

Fixed.
