### ISSUE TITLE
Slider VALUE_CHANGED

### ISSUE THREAD

**Issue by BudoNL** [eez-open/studio#655]
**Describe the bug**
LVGL with EEZ Flow
I have a Slider with VALUE_CHANGED event which triggers IsTrue action.
It seems that action is not being triggered.

**To Reproduce**
1. Add new "value:integer" variable.
2. Add slider and bind it to a value variable.
3. Add new Flow:VALUE_CHANGED event on slider widget.
4. Add IsTrue action which check value >= 10. If Yes, do whatever.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.20.0

** LVGL version (if used)**

- 8.x AND 9.x

**Comment by mvladic** [comment]
I can't tell what the problem is without seeing your project. 

Here is a project where I do what you described. There is two cases implementing same thing, in one I use VALUE_CHANGED and in the other I use the Watch action.

[lvgl_slider.zip](https://github.com/user-attachments/files/18013953/lvgl_slider.zip)

**Comment by BudoNL** [comment]
Thanks a lot for your answer and help!

I was trying to simulate the loading process by using delay and setting value to that variable.
When new value is set, it seems that slider doesn't fire the event.

Please find modification of your attached example.
[lvgl_slider.zip](https://github.com/user-attachments/files/18023195/lvgl_slider.zip)

**Comment by mvladic** [comment]
> When new value is set, it seems that slider doesn't fire the event.

Yes, you are right. But, this is how LVGL works. If slider value is changed by calling `lv_slider_set_value` and not by user interaction then VALUE_CHANGED will not be fired. So, in your case you should Watch solution.

**Comment by BudoNL** [comment]
Thank you very much!
How about using Bar?

My goal is to have a global variable loadingProgress which I will be handled by main code.
When I perform Setup(){} of Arduino and doing initialization, this variable will be incremented, and Bar will display the progress.
Once Bar is at 100%, using Flow diagram I will change to another Main screen.

**Comment by mvladic** [comment]
You can use Watch from the flow to monitor changes in the `loadingProgress` native global variable. But, you need to call `lv_task_handler` for the screen to be updated by the LVGL and `ui_tick` for the flow to keep running, in this case not only from the `loop` but also from the `setup`. For example, your `setup` could look something like this:

```
// ...
#include "ui.h"
#include "vars.h"

// ...

void setup() {
    // ...
    lv_init();

    // ...
    ui_init();

    // ...
    set_var_loading_progress(0);
    while(get_var_loading_progress() != 100) {
        // here comes your code that does loading and updates loadingProgress variable
        // ...
        // set_var_loading_progress(...);
        // ...

        // update screen
        lv_task_hander(); // or lv_timer_handler() if you are using that call

        // keep flow running
        ui_tick();
    }

    // ...
}

void loop() {
    lv_task_hander();
    ui_tick();
    delay(5);
}
```

**Comment by BudoNL** [comment]
Got it, thanks a lot Martin!
I will close this item since it seems like a LVGL architecture thingy.
