### ISSUE TITLE
GUI Actions ( showpage ) not appearing in listt with a lvgl-flow projec ( appears when it is  a dashboard)

### ISSUE THREAD

**Issue by ghisbo** [eez-open/studio#672]
**Describe the bug**
when i create a project with LVGL-FLOW, the  GUI Actions do not contain "SHOWPAGE"

**To Reproduce**
Create a project with LVGL-FLOW
Add a button
add an event ( type flow ) 
in the action list, the ShowPage is not available

**Expected behavior**
the showpage and some more should be there

**Screenshots**
![image](https://github.com/user-attachments/assets/491e9088-1057-4055-b759-f0256bd9e493)

**Desktop (please complete the following information):**
 - Win
 - Version 11

** LVGL version 9.x

eez studio v0.21

**Comment by mvladic** [comment]
In the LVGL projects you should use LVGL action with the "Change Screen" for this:

![image](https://github.com/user-attachments/assets/d71a3858-05c3-47f0-9ef3-137769d63d21)

![image](https://github.com/user-attachments/assets/b78c4826-5eec-4678-82e0-57594930c129)

![image](https://github.com/user-attachments/assets/f34400e8-be1a-4c25-93f1-db3a58902efd)

**Comment by ghisbo** [comment]
Perfect
