### ISSUE TITLE
Invalid y-axis unit in charts

### ISSUE THREAD

**Issue by mvladic** [eez-open/studio#70]
When chart is loaded and shown inline inside history, y-axis unit is voltage which is false:

![image](https://user-images.githubusercontent.com/449788/53633627-5259a880-3c18-11e9-8e7e-7dfd21bd5cb7.png)

Only after we open chart in full-screen it will show true unit which is frequency in this case:

![image](https://user-images.githubusercontent.com/449788/53633653-63a2b500-3c18-11e9-9b8a-8bb047ce28be.png)

**Comment by prasimix** [comment]
Fixed
