### ISSUE TITLE
JavaScript input dialog for time does not accept it's own scaled values

### ISSUE THREAD

**Issue by AndersWestman** [eez-open/studio#81]
EEZ Studio Version: 0.9.3
Can be reproduced in e.g. H24005 "Dlog start" script.
Saved/default values greater than 1000 converts to "ks" and does not accepts by the dialog.
1000s ---> 1ks
1h ---> 3.6ks

**Comment by mvladic** [comment]
1000 will not be converted to "ks" anymore. Only "s", "ms", "us", "ns" and "ps" are accepted.

**Comment by prasimix** [comment]
Fixed
