### ISSUE TITLE
Does not recognize PNG file from Siglent SDS oscilloscope

### ISSUE THREAD

**Issue by vestom** [eez-open/studio#86]
Siglent SDS2000X+ oscilloscope makes a screenshot by using the :PRINt PNG command which returns a binary PNG file. However the PNG file is not recognized as such (see image)

![image](https://user-images.githubusercontent.com/10729057/91637796-43210a00-ea0b-11ea-917d-29e7ea4f2af2.png)

**Comment by prasimix** [comment]
Could you please provide a sample of that binary file acquired by other method (i.e. copy to USB flash, etc.) and attach it zipped here?

**Comment by vestom** [comment]
Obtained by using Python pyvisa:
```
    sds.write("PRIN PNG")
    result_str = sds.read_raw()
```

![SCDP](https://user-images.githubusercontent.com/10729057/91637923-1caf9e80-ea0c-11ea-829b-4167268c4d3c.png)

**Comment by prasimix** [comment]
I presume that you can afterwards successfully import and display that file in EEZ Studio by using `Attach file` option?


![Screenshot from 2020-08-29 15-34-27](https://user-images.githubusercontent.com/15106476/91638089-41f0dc80-ea0d-11ea-8564-d4c924ae63a5.png)

**Comment by vestom** [comment]
Yes, that works fine :-)
I presume that EEZ Studio should be able to recognize the received binary data as a PNG file itself though?

**Comment by prasimix** [comment]
It seems that we have some issue with recognizing file header at the beginning of file transfer. @mvladic has to check that.

**Comment by vestom** [comment]
OK. (Just an off-topic question: Is there some documentation for the JavaScript API for making advanced macros? (e.g. like session.addChart())

**Comment by prasimix** [comment]
> OK. (Just an off-topic question: Is there some documentation for the JavaScript API for making advanced macros? (e.g. like connection.acquire() and session.addChart())

No, we are missing that as user manual in general :(.
I believe that @mvladic could at least make you a list of what is available/supported for JS.

**Comment by prasimix** [comment]
`:PRINt PNG` result cannot be handled properly because that is not valid SCPI query command. Query command has to end with question mark. Therefore its correct format should be `:PRINt? PNG`. One possibility to handle such command is to receive its binary and then retroactively automatically or by adding a new option like "Convert to data block" convert received binary to a PNG image.

**Comment by prasimix** [comment]
Closed, due to no response. Reopen if necessary.
