### ISSUE TITLE
List generated with table is not transferred correctly

### ISSUE THREAD

**Issue by prasimix** [eez-open/studio#87]
List generated as table looks like this:

![Screenshot from 2020-09-21 23-57-21](https://user-images.githubusercontent.com/15106476/93825810-47d18a80-fc66-11ea-8a31-31dbc0e37b92.png)

... but dwell time is not correctly transferred to the BB3 and an additional dwell time in second row is added:

![step test bb3](https://user-images.githubusercontent.com/15106476/93825947-88310880-fc66-11ea-88b2-0366d9b0943f.jpg)

Exported zipped list: [Step test.zip](https://github.com/eez-open/studio/files/5258360/Step.test.zip)

**Comment by mvladic** [comment]
Fixed.
