### ISSUE TITLE
SCPI commands and queries definitions

### ISSUE THREAD

**Issue by prasimix** [eez-open/studio#9]
ESP: Provide extended syntax definition for commands and queries
ESW: Use above mentioned definition when copy selected command or query to command line

Add definitions of expected SCPI command and query results (e.g. bitmap, csv, etc.) for better support of instruments that don't follow basic SCPI syntax (e.g. Siglent spectrum analyzer, see #31).

**Comment by Rerouter** [comment]
http://old.siglentamerica.com/USA_website_2014/Documents/Program_Material/Programming%20Guide.pdf

Page 123 defines how this data should be handled.

**Comment by Rerouter** [comment]
Just wondering if there is a formal explanation of how you would like new instruments defined, I've put together about 70% of the siglent SDS1104X-E in the same flavor as the rigol extensions, and the monstrous help documentation, but would like to make sure it all meets spec.

**Comment by prasimix** [comment]
We're working on it, step-by-step instructions how to create instrument extension will be included into M3 release

**Comment by prasimix** [comment]
Fixed
