### ISSUE TITLE
Timeout (no response to IDN query)

### ISSUE THREAD

**Issue by gojimmypi** [eez-open/studio#93]
Typically after BB3 (v1.4) awakening from standby mode, EEZ Studio will complain about an IDN query when attempting to connect. Restarting EEZ Studio does not help. Doing a soft restart on the BB3 seems to resolve.

![image](https://user-images.githubusercontent.com/13059545/97936944-0ab2ea80-1d32-11eb-9430-62102a8a2f3a.png)

![image](https://user-images.githubusercontent.com/13059545/97937008-3c2bb600-1d32-11eb-91dd-00115fb8c91e.png)

**Comment by mvladic** [comment]
Can you attach Wireshark dump?
