### ISSUE TITLE
Screendump in BMP format from Siglent SDS1xxxX-E scope not recognized 

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#94]
This issue is different from issue #86 but the solution might be very similar.

The BMP data from the SCDP is not recognised as a bitmap on my Siglent SDS1204X-E scope. Testen both on port 5024 (telnet) or 5025 (sockets).
![EEZ-Studio-Screenshot screendump issue](https://user-images.githubusercontent.com/8796121/98174914-eacc2400-1ef5-11eb-9de9-91979cb6f609.png)

Using the following script to download a BMP:
```python
import pyvisa as visa

def main():
  _rm = visa.ResourceManager()
  sds = _rm.open_resource("TCPIP::xx.xx.xx.xx::INSTR")
  print(sds.query("*IDN?"))
  sds.chunk_size = 20*1024*1024 #default value is 20*1024(20k bytes) sds.timeout = 30000 #default value is 2000(2s)
  file_name = "SCDP.bmp" 
  sds.write("SCDP")
  result_str = sds.read_raw()
  f = open(file_name,'wb') 
  f.write(result_str)
  f.flush() 
  f.close()

if __name__=='__main__': 
  main()
```

Results in a BMP file (in zip because of GitHub limitation):
[SCDP.bmp.zip](https://github.com/eez-open/studio/files/5490832/SCDP.bmp.zip)

Uploading this in EEZ-Studio works fine:
![EEZ-Studio-Screenshot Siglent BMP upload](https://user-images.githubusercontent.com/8796121/98175418-e05e5a00-1ef6-11eb-9f5d-9ec5aed7e009.png)

**Comment by mvladic** [comment]
In the #86 we added a special query return type called "Non standard data block" to handle such cases. But, in this case, SCDP is not even query so you can't specify return type. It seams that only solution is to use some kind of heuristics to detect that block of data returned by the instrument is bitmap.

![image](https://user-images.githubusercontent.com/449788/98223440-5e9c1a00-1f52-11eb-99c9-307dc8ee2ea8.png)

![image](https://user-images.githubusercontent.com/449788/98223449-6360ce00-1f52-11eb-9cdd-ea85ce38cb18.png)

**Comment by mvladic** [comment]
Option added for the SCPI commands called "This command sends back data block":

![image](https://user-images.githubusercontent.com/449788/98236586-e4749100-1f63-11eb-9955-48059da96899.png)

You can download latest windows version from here: https://github.com/eez-open/studio/releases/tag/nightly-build. Let me know if you need Linux build.

Also, here is the extension I created for testing: https://github.com/mvladic/studio-experimental-extensions

**Comment by fietser28** [comment]
I'm on OS X, did a git pull and a npm build. :-)
Imported the experimental extension you created.

![Screenshot working SCDP](https://user-images.githubusercontent.com/8796121/98245731-a7170000-1f71-11eb-8480-e6fa526b955b.png)
It works, thank you!
