### ISSUE TITLE
Script Addition Throws Error Unless "Type" is Changed

### ISSUE THREAD

**Issue by PalantirWielder** [eez-open/studio#95]
![image](https://user-images.githubusercontent.com/20051875/104399956-ba20f000-551f-11eb-931c-2866802391c4.png)

- Go to BB3 tab
- "Connect" to BB3 (Ethernet is what I tested)
- Go to Scripts ("Play" button on left column)
- "+" button to add a script
- Type in Name for script
- Leave Type as "SCPI"
- Click "OK"

This results in an error being displayed "Please fill out this field" under the "Type" selection.

If I drop down that list and click on the already checkmarked "SCPI", then this error persists and "OK" clicks are ignored.
If I click something _other than_ SCPI _then_ select SCPI the error goes away and "OK" can be clicked.

I'm running EEZ Studio 0.9.7 on macOS Catalina

**Comment by prasimix** [comment]
Fixed
