### ISSUE TITLE
Firmware info for DIB modules without MCU looks confusing

### ISSUE THREAD

**Issue by prasimix** [eez-open/studio#96]
Reported by victorhooi at [EEVblog forum](https://www.eevblog.com/forum/crowd-funded-projects/eez-bench-box-3-sequel-to-eez-h24005/msg3415422/#msg3415422):

_I also tried to use EEZ Studio to update the module firmware from my macOS machine._
_However, it didn't give me an option to update the firmware, and it lists the firmware as version "0.0"._
_Is that normal? Or is there some way to update the DP405 firmware?_

Firmware info for DIB modules without MCU looks confusing therefore we have to use e.g. `-` or `n/a ` in both `Firmware` and `All firmware release` columns.

**Comment by mvladic** [comment]
Fixed.
