### ISSUE TITLE
Encoder increment/decrement leads to confusing display

### ISSUE THREAD

**Issue by duncairn** [eez-open/studio#97]
When the encoder is used to set the voltage or current, the display removes trailing 0s and is then justified. This leads to the displayed setting moving about  horizontally and the lower digits can be confusing. For instance, when set to increment by 25mV the display may go: 4.1V, 4.125V, 4.15V, 4.175V, 4.2V, etc. Since the display is center justified, the '4.1' part moves left and right and it's difficult to keep track of the mV values incrementing since, from step to step, the same column may be showing tens of mV or hundreds of mV. Even unchanging columns appear to change since they move left and right at each step.

Contrast with setting the step to 100mV, where the display goes 4.1V, 4.2V, 4.3V, etc. In this case it is easy to see which column is changing and how close to the desired setting it is getting.

There are two possible fixes:

1. When changing the display, use left justification.

2. When changing the display, don't remove trailing digits (that is, have it display, for instance, 4.100V).

After setting, either with a short timeout or because the setting has been accepted, the display can revert to center justification and trailing 0s removed.

**Comment by prasimix** [comment]
Please report this in firmware repo: https://github.com/eez-open/modular-psu-firmware/issues
